### ISSUE TITLE
[question] Database not updated second time

### ISSUE THREAD

**Issue by tomvo** [hyperoslo/Sync#103]
I'm testing the sync functionality and all seems to work fine in my initial data request (viewDidLoad). I fetch the JSON from the server, pass it to Sync and my CoreData gets updated nicely. 
However, when I make a change server side a few seconds later and do a refresh I can see the modified JSON coming in but Sync doesn't seem to sync the changes to the database?

Any idea what this might be?

**Comment by 3lvis** [comment]
@tomvo Hi Tom! I'll update one of our demos to have a pull to refresh to make sure that updates are working properly.

Other thing, is important that you call `Sync` again only when you know the previous `Sync` operation has finished, otherwise Core Data might go nuts with threading.

**Comment by tomvo** [comment]
I solved my problem, it had nothing to do with your library but it had to do with the `SwiftRecord` library. (https://github.com/arkverse/SwiftRecord) I was using that to fetch the new results in the `onComplete` request but it did not return the new values synced. I'll raise an issue there.

Thanks for your reply and all your efforts!

**Comment by 3lvis** [comment]
@tomvo Don't worry! Have a great day :grin:
