### ISSUE TITLE
Inserting Additional Entities

### ISSUE THREAD

**Issue by bonebox** [hyperoslo/Sync#106]
In our service, we can have multiple markets, but these markets are retrieved individually and separately, not as one large request.  I noticed that if I retrieve an initial market and insert it using Sync, then retrieve a subsequent (different) market and insert it, it removes the first market from Core Data, and so on, even if they have different `remoteID`s.  This is fine if you are feeding it one huge JSON with your entire model, but would it be possible to support use cases like ours, where you may be retrieving new entities separately and needing to add them into the existing Core Data model, instead of overwriting everything?

**Comment by 3lvis** [comment]
Hi @bonebox, the `predicate` attribute might be helpful here. Giving a predicate to Sync it tells it to only sync the attributes that comply to the predicate. When a predicate is not present Sync will diff all the changes removing the elements that are not present in the JSON.

**Comment by bonebox** [comment]
Hey @3lvis! Thanks for the info. I'm having trouble determining what the predicate would look like in this case.  I tried `let predicate = NSPredicate(format: "remoteID = %@", marketID)` which seemed to work at first--the second market entity was added without removing the first.  But then I also noticed that when I inserted the second market, the items in the first market got duplicated.  Syncing the first market again fixes the duplication.

**Comment by bonebox** [comment]
Well the duplication I'm seeing seems to be somewhat random--I tried some different markets (that had fewer items) and it didn't occur with them.  The multiple markets get retrieved and subsequently Sync'd more or less concurrently--I'm wondering if that could be an issue?

**Comment by 3lvis** [comment]
@bonebox How many entries there are in the JSON you're using for updating? 2 or 1?

I can make a test case in out tests projects to check what's the problem behind it, personally I've only used Sync for the main sync (the one with all the entries in the JSON). For updates I fetched the item in a background thread and made the updates there.

If this is something we can automate it would be fantastic!

**Comment by bonebox** [comment]
@3lvis I was syncing a single market at a time, just testing with 2 of them, so 2 calls to the sync method.  Each market has varying items, but typically between 25-50.  The markets and items have a many-to-many relationship, not sure if that makes a difference.

The duplication issue was partially my own fault--I had set up a test and forgot to disable it so it was attempting to sync the same markets twice. So the sync method was getting called 4 times instead of 2. Still not sure why it duplicated the market items instead of replacing them since it was the same market, but after disabling the additional syncs it stopped duplicating things.  So using the predicate I posted above seems to be working for my situation.  Thanks for the help!

**Comment by bonebox** [comment]
Also wanted to mention that my app re-syncs the data whenever the page is refreshed, and that is working correctly (no duplicated items), so it seems that the issue has something to do with the sync method calls occurring so close together.  I did a test by wrapping the sync method call in a GCD synchronous queue and the duplication still occurred when doing the 4 concurrent calls to sync like I mentioned above.

**Comment by 3lvis** [comment]
@bonebox If you're using AFNetworking I would recommend something like AFUniqueGet, works quite well for multiple GET calls to the same resource.

https://github.com/3lvis/AFHTTPSessionManager-AFUniqueGET

**Comment by 3lvis** [comment]
@bonebox Two or more syncs to the same entity shouldn't happen at the same time, there could be some inconsistency in the persistent store and you'll get crashes saying.

"Couldn't not fullfill fault.."
