### ISSUE TITLE
Decouple from DATAStack. F.ex.: use <NSManagedObjectContextProvider> instead?

### ISSUE THREAD

**Issue by lukaszmargielewski** [hyperoslo/Sync#107]
This is just an idea: 
I think, having the access to the proper NSManagedObjectContext is enough for sync engine.
If there are special 'query' helpers needed, just create context extension class.

**Comment by 3lvis** [comment]
Interesting idea @lukaszmargielewski!

**Comment by 3lvis** [comment]
This would be a nice feature but the downsides will be quite considerable. For example an increase of support cause by bugs in other frameworks.

Closing this one, sorry.
