### ISSUE TITLE
I need help getting started with your great Library

### ISSUE THREAD

**Issue by Gerungofulus** [hyperoslo/Sync#108]
Hi there!

I am sorry for bothering you but I tried to get this running for two hours right now and I seem to be stuck.

I am using the following setup in CoreData
![bildschirmfoto 2015-06-22 um 23 06 48](https://cloud.githubusercontent.com/assets/9848525/8293067/6334dc44-1933-11e5-84eb-37e48845642d.png)

and I have an [NSDictionary] array (that I formed out of a json response). 
(I don't get to choose the json response and I get the same error using the json response instead of the array so I figured that I could go on in using the array.)
```Swift
[{
    id = 224f02078c4278c2;
    name = "Pascal Blunk";
    ownCollection = 0;
    owner =     {
        id = 32492cc981632817;
        name = "Pascal Blunk";
    };
}, {
    id = e393ed8b0c1368fc;
    name = pascal7;
    ownCollection = 1;
    owner =     {
        id = 739b7ba364ddd874;
        name = pascal7;
    };
    users =     (
        739b7ba364ddd874
    );
}]
```
Every item in that array is a specific collection. The owner property is an object of type User. Users is an array of user_ids. I used to fill in the CoreData myself but now I want to switch to your powerful code. When primitively calling Sync.changes with the array given I get the following stack trace
```
2015-06-22 22:54:19.615 Grocli[11780:3544854] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<__NSCFString 0x7ff821c5dcb0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key id.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010dd31c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010d9cabb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010dd318a9 -[NSException raise] + 9
	3   Foundation                          0x000000010d40582a -[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 226
	4   Foundation                          0x000000010d35eb23 -[NSObject(NSKeyValueCoding) valueForKey:] + 251
	5   Foundation                          0x000000010d35e914 -[NSArray(NSKeyValueCoding) valueForKey:] + 437
	6   Grocli                              0x000000010cd08bf7 -[NSManagedObject(Sync) sync_processToManyRelationship:usingDictionary:andParent:dataStack:] + 1095
	7   Grocli                              0x000000010cd083de -[NSManagedObject(Sync) sync_processRelationshipsUsingDictionary:andParent:dataStack:error:] + 606
	8   Grocli                              0x000000010cd0ac2c __78+[Sync changes:inEntityNamed:predicate:parent:inContext:dataStack:completion:]_block_invoke + 172
	9   Grocli                              0x000000010ccfdcc6 +[DATAFilter changes:inEntityNamed:localKey:remoteKey:context:predicate:inserted:updated:] + 1942
	10  Grocli                              0x000000010cd0a934 +[Sync changes:inEntityNamed:predicate:parent:inContext:dataStack:completion:] + 1748
	11  Grocli                              0x000000010cd09a99 __61+[Sync changes:inEntityNamed:predicate:dataStack:completion:]_block_invoke + 121
	12  Grocli                              0x000000010cd014ba __43-[DATAStack performInNewBackgroundContext:]_block_invoke + 58
	13  CoreData                            0x000000010cfd7a79 developerSubmittedBlockToNSManagedObjectContextPerform + 201
	14  libdispatch.dylib                   0x0000000110a7c614 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x0000000110a636a7 _dispatch_queue_drain + 2176
	16  libdispatch.dylib                   0x0000000110a62cc0 _dispatch_queue_invoke + 235
	17  libdispatch.dylib                   0x0000000110a663b9 _dispatch_root_queue_drain + 1359
	18  libdispatch.dylib                   0x0000000110a67b17 _dispatch_worker_thread3 + 111
	19  libsystem_pthread.dylib             0x0000000110de9637 _pthread_wqthread + 729
	20  libsystem_pthread.dylib             0x0000000110de740d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
I am not quite sure, but I would guess, that the code fails when it comes to handling the array 'users' since there is no 'id' field given. So I basically have two questions: a) Do you think that this is the problem and b) Can I somehow tell your code that it should handle all items in the users array as IDs?

**Comment by 3lvis** [comment]
Hey Pascal! You can change `users` in `Collection` to be an attribute instead of a relationship, then you could set it as `Binary Data`, this will tell Sync to store it as an array of strings. Also I would advise you that maybe renaming it to `userIDs` might be a good idea so you know it's not an array of users. Also so you can keep your original relationship to users.

https://github.com/hyperoslo/Sync#arraydictionary

Finally Sync will try to map `userIDs` to `user_ids`, so you might need to change the `hyper.remoteKey` to make it point to `users`.

https://github.com/hyperoslo/Sync#attribute-mapping

----

I hope this was useful, just ping me if this doesn't work. 

Best,

**Comment by Gerungofulus** [comment]
Hi Elvis, 
thanks for your great help! It works just fine now. Just let me ask two more questions:
1st:Can I use multiple primary keys? 
In this specific case I would want to have the fileurl and the remoteID to be unique, because again I don't get to change the API, but I would like to add a PhotoItem with a given url. I would then get the id created on the server when polling all photo items later on and I would need to update the photo item in my local database to the id returned from server.
2nd: Is it possible to disable deletion in sync on special requests?

Thanks again for your great help!

Take care,
Pascal

**Comment by 3lvis** [comment]
Hey! It's nice to hear that you go it working.

>1st:Can I use multiple primary keys? 

1.- We don't have support for this out of the box, but it shouldn't be difficult to add support for it if you feel like doing that.

First, `DATAObjectIDs` should support multiple attributes, second `DATAFilter`, finally it would be needed to add support in `Sync`.

>2nd: Is it possible to disable deletion in sync on special requests?

2.- Yes, it's possible, when you use Sync you should provide a predicate that gives you only the elements that you want to sync, if you want to skip some you can do.

>Alternatively if you only want to sync users that have been created in the last 24 hours, you could do this by using a NSPredicate.

This will disable deletion in all the items that don't apply to the predicate.

```objc
NSDate *now = [NSDate date];
NSDate *yesterday = [now dateByAddingTimeInterval:-24*60*60];
NSPredicate *predicate = [NSPredicate predicateWithFormat:@"createdAt > %@", yesterday];

[Sync changes:JSON
inEntityNamed:@"User"
    predicate:predicate
    dataStack:dataStack
   completion:^{
       //...
    }];
```

Let me know if I can help in anything else, I'll be closing this issue for now.

**Comment by Gerungofulus** [comment]
Hey Elvis, 
thanks again for that quick response! I will definitely take a look at adding multiple primary keys. If I do so, I will inform you about it.
For so long the next quesiton should be the last: The property collectionID in my GrocliPhotoItem happens to not be the id of the collection itself, but the whole collection. Now I would want to use the PhotoItem I retrieve (JSON):
```
{
    collectionId = e393ed8b0c1368fc;
    fileurl = "e393ed8b0c1368fc/437BBC0F05384B9B822A.jpg";
    id = b53b9e849a129978;
    isBought = 0;
}
```
and add those to my database but obviously this would not work since. collectionID in my database is an object of type collection. CouldI use a predicate saying that I want to only update PhotoItems with ```collectionID.remoteID == collectionId``` ?

Have a great evening! Whenever you come to Berlin reach out and we will get you a beer or whatever your heart desires ;)

**Comment by 3lvis** [comment]
I don't really understand your last question. You want to sync only items in the array of `PhotoItem` where `collectionID` is not nil?

**Comment by Gerungofulus** [comment]
Yes I want to sync those Photoitems, where ```collectionID.remoteID == 3393ed8b0c1368fc```

**Comment by 3lvis** [comment]
@Gerungofulus something like this could work in an array of GrocliPhotoItems

```objc
NSPredicate *predicate = [NSPredicate predicateWithFormat:@"collectionID == %@", @"3393ed8b0c1368fc"];

[Sync changes:JSON
inEntityNamed:@"GrocliPhotoItem"
    predicate:predicate
    dataStack:dataStack
   completion:^{
       //...
    }];
```

**Comment by 3lvis** [comment]
Or maybe

```objc
Collection *collection = //... fetch collection for ID 3393ed8b0c1368fc
[Sync changes:JSON
inEntityNamed:@"GrocliPhotoItem"
    parent:collection
    dataStack:dataStack
   completion:^{
       //...
    }];
```

**Comment by Gerungofulus** [comment]
The latter one helped. Thanks made! Though I find the name for parent somehow confusing since I expected it to be inheritance related.

**Comment by 3lvis** [comment]
@Gerungofulus Any suggestions on how to make it more clear? Maybe adding appledocs to Sync would help.

**Comment by Gerungofulus** [comment]
Yeah some kind of documentation in that regard would definitely help. If you didn't mind I would write some documentation on those functions and send it to you in about a week

**Comment by 3lvis** [comment]
@Gerungofulus that would be fantastic :star2: :star2: :cake: :star2: :star2:

**Comment by Gerungofulus** [comment]
BTW I have another issue. When syncing the collections, sometimes collections are deleted but the pictures belonging to those collections are not. Of course I get an CoreData Error when doing this. Since I made the relationship to a collection mandatory this will make the managedObjectContext save with an error, which I would like to avoid. So the question is: Can I make Sync perform additional deletes on items that lost a mandatory relationship? Is there any possibility to get control on all changed items? Is anything in that regard planned?

**Comment by Gerungofulus** [comment]
Of course I could just make this relationship optional and update all items which lost that connection after the sync but I would rather like the database to be consistent at all times.

**Comment by Gerungofulus** [comment]
And I think that using the contextWillSaveNotification would be strange since I might also have other core data using frameworks (like Googe Analytics etc.) Since I could not listen for a specific managedObjectContrext because Sync uses background managedObjectContexts. And I'd rather not wait for errors to occurr.

**Comment by Gerungofulus** [comment]
Okay obviously I can delete items with mandatory realtionships by using the cascade deletion rule, but it be cool to get at least the deleted items in return.

**Comment by 3lvis** [comment]
>Okay obviously I can delete items with mandatory realtionships by using the cascade deletion rule, but it be cool to get at least the deleted items in return.

Hey Pascal,

I don't really understood your last comment, is there anything specific that we could do to help you? I don't understand the `get the deleted items in return`. You mean that instead of automatically deleting the items you would do it manually?

**Comment by Gerungofulus** [comment]
I just thought that there might be usecases where one would like to get some information about what has been changed by Sync. Which items have been deleted/updated/added for example

**Comment by 3lvis** [comment]
@Gerungofulus like improved logging on what's going on?

**Comment by Gerungofulus** [comment]
Yes for example. Or if you would like to be informed when certain items change or things like that.

**Comment by 3lvis** [comment]
@Gerungofulus got it! I made a task for it. https://github.com/hyperoslo/Sync/issues/109 :)

**Comment by Gerungofulus** [comment]
I won't make it with the Apple Docs this month, but I'll try to get it done in August. I'm really sorry about it.

**Comment by 3lvis** [comment]
@Gerungofulus Don't worry Pascal! Thanks for taking the time to comment here. I hope everything is good in Berling :grin:
