### ISSUE TITLE
Improve logging of updated, inserted and removed items

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Sync#109]
Would be great if we had better logging of what happens when Sync is performed, this would help for example when debugging issues.

**Comment by tommypeps** [comment]
Which this line you can see  any change over the main context 

```Objective-C
- (void)viewDidLoad
{
.
.
.

    [[NSNotificationCenter defaultCenter]addObserver:self
                                            selector:@selector(NotificatorChange:)
                                                name:NSManagedObjectContextObjectsDidChangeNotification
                                              object:self.dataStack.mainContext];
.
.
.
}
...........
-(void)NotificatorChange:(NSNotification*)notification
{
    NSSet *updatedObjects   = [[notification userInfo] objectForKey:NSUpdatedObjectsKey];
    NSSet *deletedObjects   = [[notification userInfo] objectForKey:NSDeletedObjectsKey];
    NSSet *insertedObjects  = [[notification userInfo] objectForKey:NSInsertedObjectsKey];

}

```

**Comment by 3lvis** [comment]
@tommypeps :clap:

**Comment by 3lvis** [comment]
This is much better than what I thought. I'll add it to the FAQ

**Comment by 3lvis** [comment]
https://github.com/hyperoslo/Sync#logging-changes

**Comment by bilics** [comment]
Hi, great library - thanks!

I am trying to use NSNotifications to update the UI (a progress bar).

However, NSManagedObjectContextObjectsDidChangeNotification only gets called at the very end 
 - after all objects have been added (or updated). Since I am updating ~10.000 objects, the user keeps waiting for the UI to start moving... 

Is there a way I can force the notifications to be fired during execution ?

Thanks!

**Comment by 3lvis** [comment]
Hi @bilics, Sync uses the built-in notification system by Core Data to send notifications. I'm not sure if adding another layer of notifications would be a good thing to do at this point. Maybe changing your Core Data stack would let you achieve what you are looking for. Sorry for not being more helpful :)
