### ISSUE TITLE
Work with nested properties

### ISSUE THREAD

**Issue by ares-huy-le** [hyperoslo/Sync#111]
I have a nested JSON ex:
{
"name":"Huy",
"contact": {
    "skype":"huyle",
    "email":"huy@mail.com"
}

How I can flat them into 1 ManagedObject? Ex: 
User
- name
- skype
- email

**Comment by 3lvis** [comment]
Hi Huy!

We don't have support for flattening dictionaries. One way you can achieve this with the current version of Sync is storing `contact` as a dictionary. 

- Add a `contact` attribute to your Core Data model
- Set the type of `contact` to `Binary Data`

This issue can help you:

https://github.com/hyperoslo/Sync/issues/87
