### ISSUE TITLE
Crash when mapping many-to-many

### ISSUE THREAD

**Issue by Nik09** [hyperoslo/Sync#113]
Crash when mapping many to many relationship in `NSManagedObject+Sync#sync_processToManyRelationship:usingDictionary:andParent:dataStack : 116`, uses remote relationship name on entity, for ex, should be likedPosts instead of liked_posts.

**Comment by 3lvis** [comment]
Could you share an screenshot of your Core Data model and an example of your JSON, please?

https://github.com/hyperoslo/Sync/blob/master/CONTRIBUTING.md

**Comment by Nik09** [comment]
Sure.
`[
  "id": 2
  "text": "test"
  "liked": [
    {
      "id": 1
      "name": "user test"
    }
]`

Core Data:
Post (remoteID, text, liked[has_many: User])
User (remoteID, name, likedPosts[has_many: Post])

So what it does, it tries to call `#mutableSetValueForKey:` on `User` with `liked_posts`, ie using remote name

**Comment by 3lvis** [comment]
Thanks @Nik09! I'll take a look later today.

Could you share an screenshot of your Core Data model? Might help to check how the relationships have been set.

**Comment by 3lvis** [comment]
@Nik09 This should be fixed on `master`, would you mind checking it everything is fine now? :dancers:

**Comment by 3lvis** [comment]
@Nik09 I just pushed 1.0.6 this should fix your problem <3

https://github.com/hyperoslo/Sync/releases/tag/1.0.6
