### ISSUE TITLE
Need help for Data Model 

### ISSUE THREAD

**Issue by samouds** [hyperoslo/Sync#114]
Hello,

I need some help for creating the Data Model based on this JSON :  

```json
{
"posts": [
    {
      "id": "",
      "title": "",
      "author": {
        "id": "",
        "name": ""
      },
      "related": {
        "id": "",
        "name": ""
      },
      "original_post": {
              "id": "",
              "title": "",
              "author": {
                "id": "",
                "name": ""
              },
              "related": { ... },
              "original_post": { ... }
       }
    }]
}
```

Thanks a lot !

**Comment by 3lvis** [comment]
So a Post can have an Original Post inside and this Original Post can have an Original Post inside, right?

You can have Post ==(to many)==> Original Post ==(recursive to itself)==> Original Post

**Comment by 3lvis** [comment]
Here's an example of a recursive relationship. You can find it in the [Tests project](https://github.com/hyperoslo/Sync/blob/master/Tests/Tests/Tests.m#L334-L370):

https://github.com/hyperoslo/Sync/tree/master/Tests

<img width="611" alt="screen shot 2015-08-15 at 04 37 28" src="https://cloud.githubusercontent.com/assets/1088217/9287131/6c9baee0-4307-11e5-80bf-b71d8f17f44d.png">

<img width="630" alt="screen shot 2015-08-15 at 04 37 35" src="https://cloud.githubusercontent.com/assets/1088217/9287132/7123bb06-4307-11e5-8541-75b978eb6185.png">

<img width="419" alt="screen shot 2015-08-15 at 04 37 43" src="https://cloud.githubusercontent.com/assets/1088217/9287134/7590ee16-4307-11e5-8d36-68b03a2b726d.png">

I hope this was helpful :v:

**Comment by samouds** [comment]
Thanks @3lvis, I will try this one :)
