### ISSUE TITLE
[Question] Is it possible to only add/update records but not deleting unpresented?

### ISSUE THREAD

**Issue by d6u** [hyperoslo/Sync#116]
Assuming I'm building a Twitter client. I only want to fetch new tweets and save them. Old tweets not presented during a syncing should remain the same. I know I can use predicate to exclude all existing tweets to prevent them from deleted. But is there an option to not delete unpresented tweets?
If this is not a feature Sync would target, is there any alternative library to do so?

Thanks!

**Comment by 3lvis** [comment]
Hey, there's no such "feature" in Sync at the moment, but it could be way simpler than having a predicate with all the existing tweets. You could use the latest created date, updated date or the latest date when you refreshed items from the backend and say.

```objc
NSPredicate *predicate = [NSPredicate predicateWithFormat:@"createdAt > "02-01-2015 21:21:00 +000"]; // Only sync tweets after "02-01-2015 21:21:00 +000". Of course using an NSDate instead of the string that I wrote.

[Sync changes:JSON
inEntityNamed:@"Tweet"
    predicate: predicate
    dataStack:dataStack
   completion:^{
       //...
    }];
```

I don't know of other libraries that do the same than Sync that have this feature.

I hope this was useful!

:v:
