### ISSUE TITLE
Export Core Data into JSON using Sync?

### ISSUE THREAD

**Issue by galinyonchev** [hyperoslo/Sync#121]
Hello, is it possible to export my core data model into JSON file using Sync? Or at least something like that?

**Comment by 3lvis** [comment]
Hi!

One of the dependencies of Sync is [NSManagedObject-HYPPropertyMapper](https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper), this pod provides a method that converts your `NSManagedObject` into a JSON object.

```objc
User *user = //...
user.firstName = @"John";
user.lastName = @"Hyperseed";

NSDictionary *userJSON = [user hyp_dictionary];
```

You could make a fetch request to retrieve all the managed objects for an entity, then loop the result array and create a JSON array.

I hope this is useful for you :)

**Comment by galinyonchev** [comment]
And what If I have a single Patient entity object with some other entity objects like fitness data, personal data and etc. I want to export the single Patient object, but with other entities attached to it. Is this possible? Like, not loop through all objects and create the JSON array myself, but with single line of code, like this:

NSDictionary *userJSON = [patient hyp_dictionary];

I think it is something connected with the PrimaryKey or not?

**Comment by 3lvis** [comment]
@galinyonchev We don't support for that out of the box. Feel free to contribute someone else might find this useful :)

I created an issue for the task https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/issues/76

**Comment by 3lvis** [comment]
@galinyonchev hey! Now doing:

```objc
NSDictionary *dictionary = [user hyp_dictionaryUsingRelationshipType:HYPPropertyMapperRelationshipTypeArray];
```
Will also go to the entities attached to this entity and make an array representation.

https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper#json-representation-from-a-nsmanagedobject

**Comment by galinyonchev** [comment]
Hm, it is not working in my project. The app just freezes without any error messages. 
Do I have to add somewhere this "PrimaryKey" or I can go without it?

**Comment by 3lvis** [comment]
@galinyonchev Is it freezing now and it was working before? Or this is the first time you're implementing Sync?

Might be useful if you could share your Core Data model + an example of the JSON that you're using.

Is it freezing in `hyp_dictionary`?

**Comment by galinyonchev** [comment]
This is the first time I am implementing this method.
It is freezing when I push the button that calls this one:

patient.hyp_dictionaryUsingRelationshipType(.Array))

Here is my Core Data model (sorry for hiding some things):

![screen shot 2015-09-25 at 12 37 05](https://cloud.githubusercontent.com/assets/13518877/10097642/1baece3a-6383-11e5-8587-4f736480d981.png)

**Comment by 3lvis** [comment]
@galinyonchev I'll take a look this weekend :)

**Comment by galinyonchev** [comment]
I found the problem - it was because of a property with digits in its name. Now, I am trying the export my Patient object with his Baseline relationship attached to it.

I have a single Patient object with some properties and another object - Baseline (with its properties). I have a relationship between these two - inversed and of type "to-one". I am trying to export it using 

NSDictionary *dictionary = [user hyp_dictionaryUsingRelationshipType:HYPPropertyMapperRelationshipTypeArray];

but it only exports the Patient object with its properties. Any idea why?

**Comment by 3lvis** [comment]
@galinyonchev It seems that this could be caused by the inverse relationships missing.

You need inverse relationships.

If patient has many weights, then weight needs a patient.

![model-1](https://cloud.githubusercontent.com/assets/1088217/10106775/f0cad1f8-63b6-11e5-9917-10f035abcb37.png)

**Comment by galinyonchev** [comment]
I tried with inversed relationship and it was not successful. I am out of ideas and I hope you can find a solution.

**Comment by tommypeps** [comment]
```JavaScrit
[{name:nameExample,
id:uniqueID,
username:username,
data:[
{created_at:date,
id:uniqueID,
text:text},
{created_at:date,
id:uniqueID,
text:text}
,{created_at:date,
id:uniqueID,
text:text}

]

}]

**Comment by galinyonchev** [comment]
I found that on line 80:

            id relationships = [self valueForKey:relationshipName];

And guess what -  relationship is nil here. There is no value for the chosen key in self. 
I think the problem is not in my CoreData model, but something with the library?

**Comment by tommypeps** [comment]
the json work with Sync must be perfect ;)

**Comment by galinyonchev** [comment]
Here is the Patient object. The value for baseline is nil, although there is a Baseline object with some data in it. Any ideas what I have to do to make it work?

![screen shot 2015-09-28 at 10 57 57](https://cloud.githubusercontent.com/assets/13518877/10130556/478ab720-65d2-11e5-88de-bc9e11cd2052.png)

**Comment by 3lvis** [comment]
@galinyonchev https://github.com/hyperoslo/Sync/pull/123

**Comment by galinyonchev** [comment]
Thank you! Solved! It was because of my Core Data model.

**Comment by 3lvis** [comment]
:clap:

**Comment by 3lvis** [comment]
@galinyonchev Have you also set the delete rule to Cascade in the `one-to-many` relationships? I always forget that :grin:
