### ISSUE TITLE
Terminating app due to uncaught exception 'NSRangeException'

### ISSUE THREAD

**Issue by MauMaxxa** [hyperoslo/Sync#127]
"Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'"

I got this error on my first launch on every new test device
![schermata 2015-10-06 alle 23 52 41](https://cloud.githubusercontent.com/assets/10811652/10323753/66726fac-6c85-11e5-87bb-2e656826d74b.png)

this is my coredata model, and i've set id as hyper.isPrimaryKey.

Can you please help me? 
Thank you

**Comment by 3lvis** [comment]
Hi @MauMaxxa, 

Could you please share an example of your JSON too? Also, are you using any predicates? Or just calling 

```objc
[Sync changes:JSON
inEntityNamed:@"Pagina"
    dataStack:dataStack
   completion:^{
    }];
```

**Comment by 3lvis** [comment]
Closing since we didn't got more information about this issue.
