### ISSUE TITLE
Doesn't work with cocoapods' use_frameworks

### ISSUE THREAD

**Issue by 0ff** [hyperoslo/Sync#130]
Unfortunately, the latest version of Sync is not compatible with the `use_frameworks!` option of cocoa pods.
`import "DATAStack.h"` (in `NSArray+Sync.h`) needs to be changed to `import <DATAStack/DATAStack.h>` for this to work (which would fail without the option).

Any ideas on how to make this work? The option is needed to include Pods written in swift, so not using the option is not an option I fear :)

**Comment by 3lvis** [comment]
I'll have a look :)

**Comment by 3lvis** [comment]
Hi @0ff!

Sorry for this. It should be fixed now. I changed the Examples and the Tests suite to use modules. So I added `use_frameworks`. and then I did `@import DATAStack;`.

https://github.com/hyperoslo/Sync/releases/tag/1.1.0

**Comment by 0ff** [comment]
Wow, you guys rock! Fastest time from Issue to perfect resolution I've seen in a very long time! Thanks, please keep on the great work :)
