### ISSUE TITLE
Create an option to always add an Object (instead of removing)

### ISSUE THREAD

**Issue by FelipeDocil** [hyperoslo/Sync#137]
I'm working with pagination, and saw an weird behaviour using `change:`

When I request the first page, and pass the response object as parameters to `change:` it works pretty well, inserting at Core Data all the Objects was in the JSON.
But the problem happens when I request the second page, it adds the Objects that was in the second page but removes the Objects from the first page causing a wrong behaviour in my app.

There's an option to just add the response objects? Not deleting if there's not in the request JSON

**Comment by 3lvis** [comment]
Hi Felipe,

The only way at the moment is using a predicate for this. Your predicate says which items will be synced. For example you can say: "only sync items that belong to page 2", or "only sync items created after this date", or also "only sync items higher than ID: 125".

**Comment by 3lvis** [comment]
The items that don't belong to this predicate will not be deleted or updated.

**Comment by FelipeDocil** [comment]
Ok thanks, I'll try work with predicates, perhaps your idea using ID work for me.

Any plans to implement that in the future? 

(btw, you can close the issue if you want)

**Comment by 3lvis** [comment]
I have been thinking about adding something like this, I'm just afraid that adding something like this would increase the amount of support since people will suddenly start wondering why my items are not been updated or been deleted. I'll be implementing infinite scrolling on one of my apps so I'll check how to properly do this and if just having predicates will work.

I'll let you know how it works, and please let me know how challenging doing the ID predicate is for you.

Thanks!

**Comment by 3lvis** [comment]
Hi @FelipeDocil, I would like your feedback with something.

>There's an option to just add the response objects? Not deleting if there's not in the request JSON

If you were using something like that, how would you delete non existing items then? What happens if items get deleted from your backend?

**Comment by FelipeDocil** [comment]
Actually that's a nice question that I haven't think about. Until now I'll have a 'ghost' User at my database.

To fix my problem I made a method at User.m doing something like that.

```objective-c
+ (void)addUsers:(NSArray *)elements completion:(void (^)(NSError *))completion
{
	NSMutableArray *body = [[NSMutableArray alloc] init];
	[body addObjectsFromArray:elements];

	NSArray *allUsers = [self fetchAllUsers];
	[allUsers enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
		[body addObject:[self dictionaryFromUser:obj]];
	}];

	[Sync changes:body
	inEntityNamed:@"User"
	    dataStack:[Constants dataStack]
	   completion:completion];
}
```

And at `dictionaryFromUser:` I reparse all User I have at CoreData, something like `@{@"id" : user.remoteID}` and so on with all attributes User has.

Actually I have to think about how I'll do that, that's a really problem. For a work around perhaps I'll need another request just to delete the 'ghosts' Users, I don't know. Have you think a good solution?

**Comment by FelipeDocil** [comment]
Btw the `id` solution didn't work for me because I use it at a `SearchView` so, every time I searched a few Users I got all my Users deleted.

**Comment by 3lvis** [comment]
@FelipeDocil when you search you could include the search predicate to your Sync method, though.
