### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by jairobjunior** [hyperoslo/Sync#138]

**Comment by 3lvis** [comment]
Hi @jairobjunior!

I'm not a Carthage user myself, but feel free to add it with a pull request, would be awesome to have this. :heart:

**Comment by 3lvis** [comment]
Closing since @jairobjunior, doesn't seem to be interested in adding support for this :cry:

**Comment by 3lvis** [comment]
Added Carthage support on the latest version.
