### ISSUE TITLE
Importing relationships by id

### ISSUE THREAD

**Issue by jkblgithub** [hyperoslo/Sync#139]
This references closed issue #64. In that issue, the following json was presented:

```
{ "project":
    {   "id": 12345,
        "name": "My Project",
        "category": 1,
        "teamMemberIDs": [1, 2, 3, 4]
    }
 }
```

We have a similar setup and before we sync products, we sync category and teamMembers. Can Sync handle this? At the moment an exception is thrown. If it can't, can you suggest a workaround please?

PS Thanks for this library - it is excellent!

**Comment by 3lvis** [comment]
Hi @jkblgithub,

Could you share your Core Data model? Would be nice to understand the relationships.

Also I guess the exception is thrown here because the category contains just an `id` instead of a full category object. Which is what Sync wants.

Sync requires the full category object with `id`: 1 because if it's not found it will create it and attach it to project `id`: 12345.

What's the use case for teamMemberIDs? Do you have a relationship for this? Does it mean that a project has many team members?

**Comment by jkblgithub** [comment]
Hi @3lvis ,

Thanks for your quick reply. Our category entity is:

```
name (NSString)
remoteID (int)
color (NSString)
overview(NSString - quite a long string)
projects (toMany relationship)
```

The reason why we dont want to serialize the category with each project is that it would be a massive duplication of data (we have many projects and each category can have quite a lot of text in overview). That is why we import categories first using Sync and then try to import projects - we were hoping that Sync would be able to get the category record from Core Data as it had already been imported. If this cant be done with the current version of sync, perhaps a way to do this for a future release would be for a flag to be set in userinfo, indicating the relationship will be presented by an id?

I am guessing the best solution for now is for us to replace the category id in project with the necessary json ourselves before passing to sync?

**Comment by 3lvis** [comment]
@jkblgithub that's correct, a workaround would be to just replace the `"category": 1` with the full object.

```json
{
   "project":{
      "id":12345,
      "name":"My Project",
      "category":{
         "id":12345,
         "name":"My category"
      }
   }
}
```

There's a simple way to generate the `json` representation of a category. For example this is how to convert a user managed object to JSON.

```objc
User *user = [self entityNamed:@"User" inContext:dataStack.mainContext];
user.remoteID = @111;
user.age = @25;
user.driverIdentifier = @"ABC8283";
NSDictionary *dictionary = [user hyp_dictionaryUsingRelationshipType:HYPPropertyMapperRelationshipTypeNone];
```

```json
{
   "id":111,
   "age":25,
   "driver_identifier":"ABC8283"
}
```

**Comment by 3lvis** [comment]
Let me know if this fixes your problem, otherwise feel free to reopen the issue.

I'll make a new issue to see if we can add support for this in the feature.

**Comment by jkblgithub** [comment]
Thanks @3lvis 

Did not know about using HYP to create json from a managedobject - very handy.

Once again thanks for Sync and your help.

**Comment by 3lvis** [comment]
@jkblgithub you're welcome :heart:

**Comment by 3lvis** [comment]
I've been working on this in #140

Should be ready at the end of next week.

**Comment by jkblgithub** [comment]
Excellent - thank you!!
