### ISSUE TITLE
Add model naming convention to readme

### ISSUE THREAD

**Issue by kostiakoval** [hyperoslo/Sync#14]
- Property naming: `id` and `remoteID`
- Parent children Relationship naming: 'notes' and 'parentNote` or just `note`

**Comment by NSElvis** [comment]
@kostiakoval It's there https://github.com/hyperoslo/Sync#nsmanagedobject-hyppropertymapper

I think relationships and inverse can be named in any way, can't remember adding a convention for that

:)

**Comment by kostiakoval** [comment]
@NSElvis  It seams like not.
You are using  relationship.name as Entity name. so if I name my relationship 
`bigNumber` instead of `number` it wont parse it, because it will look for Entity `Bignumber`

```
- (void)sync_processToOneRelationship:(NSRelationshipDescription *)relationship
                      usingDictionary:(NSDictionary *)objectDict
{
    NSString *entityName = [relationship.name capitalizedString];
    NSManagedObject *object = [Sync safeObjectInContext:self.managedObjectContext
                                             entityName:entityName
                                               remoteID:[filteredObjectDict andy_valueForKey:@"id"]];
  ...
}
```

**Comment by NSElvis** [comment]
@kostiakoval Oh, understood. I'll verify and update the readme.

**Comment by NSElvis** [comment]
@kostiakoval I wonder if this is fixed too

**Comment by kostiakoval** [comment]
@NSElvis  but this one was changed in lat PR, so it's not valid anymore. 
Just close this one

**Comment by NSElvis** [comment]
ok :)

**Comment by kostiakoval** [comment]
`unit` -> maps properly to `OrganizationUnit` now
![screen shot 2015-03-19 at 15 37 31](https://cloud.githubusercontent.com/assets/1086260/6732720/e988f7a2-ce4d-11e4-854d-589c64a657ea.png)

**Comment by NSElvis** [comment]
sweet
