### ISSUE TITLE
Sync relationships by only providing the id

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Sync#140]
Today to sync a relationship you need the full JSON object. This is because Sync prefers to make sure that if the object isn't found in Core Data, it will just add it to Core Data and link it to the necessary objects.

For example if you had a list of projects that had a category inside (Project -- to one --> Category) the JSON should look like this:

```json
{
    "id":12345,
    "name":"My Project",
    "category":{
       "id":12345,
       "name":"My category"
    }
}
```

But if you are super sure that the category already has been inserted in Core Data and is not going to be removed while the sync operation is in progress you should be able to just send.

```json
{
    "id":12345,
    "name":"My Project",
    "category_id":12345
}
```

The requirement of the full JSON object from Sync comes from the fact that it ensures that the required category object will exist at all times, sadly not all the APIs work this way and they choose to remove this since it causes data repetition.

Related to #139 and #64.

**Comment by 3lvis** [comment]
We could add a flag to the user info in the relationship, to clarify that only the ID has been provided.

Maybe something like `hyper.justForeignKey` : `YES`

**Comment by tpmullan** [comment]
Where would be the best place to add this change?  My first guess is to add a function like sync_processToOneRelationship that only takes an id.  The function would only be called when "hyper.justForeignKey : YES" was set.  Then I can reuse sync_safeObjectInContext and add the relationship.

**Comment by 3lvis** [comment]
@tpmullan 

> break backwards compatibility

I meant that if today there are people using `category_id` to just store the category_id then it could break, but we could just find a way to not break it. :)

Right now I'm trying to figure out the other case scenarios.

1.- We have two entities: User and Category. Each category has an id and a name, each user has an id, a name and a category_id.

Here it would be easy, you first sync all your categories, then when you sync your users the categories will just get mapped. If you do it the other way (first sync users then categories there's nothing we can do, that was probably what I didn't like about this system).

2.- We have one entity: User. Each user has an id, a name and a category_id.

Here the elements get mapped, relationships don't get made.

3.- This is similar to number 1, the difference is that a user can be part of many categories. We have two entities: User and Category. Each category has an id and a name, each user has an id, a name and a category_ids (an array).

Here it would be easy, you first sync all your categories, then when you sync your users the categories will just get mapped. If you do it the other way (first sync users then categories there's nothing we can do, that was probably what I didn't like about this system).

**Comment by 3lvis** [comment]
Test models with multiple letters

**Comment by 3lvis** [comment]
Right now number 1 is being added and tested, I even added test for entities that have multiple words so: "ChallengingGoal" gets mapped to `challenging_goal_id`, if you do `lowercase` then it gets changed to `challenginggoal_id` which is not what we want.

**Comment by 3lvis** [comment]
Case number 2 should work fine in the current setup but I would like to add a test for it. Then I'll have a look at number 3, then let this feature cooldown for a bit on `master` and make a new release next Friday.

**Comment by tpmullan** [comment]
Good set of edge cases.  The way I structured my data made it work for me, but it wasn't very generic.  I will test your version this week.  Thanks!

**Comment by 3lvis** [comment]
Might be interesting to handle a special case for people that have `category` instead of `category_id`.

**Comment by violabg** [comment]
Is this already available in the current release?

**Comment by 3lvis** [comment]
@violabg Only on master.

**Comment by 3lvis** [comment]
I made a separate issue for the to-many mapping. https://github.com/hyperoslo/Sync/issues/151

Closing this.

**Comment by 3lvis** [comment]
I also improved the README so it shows that this is possible.

https://github.com/hyperoslo/Sync#relationship-mapping

**Comment by 3lvis** [comment]
This is included on 1.3.0 now

https://github.com/hyperoslo/Sync/releases/tag/1.3.0

**Comment by violabg** [comment]
Thanks for the reply.

I can't figure it out the way to structure my json in order to be converted to my model.


![screen shot 2015-12-11 at 15 48 37](https://cloud.githubusercontent.com/assets/3963176/11746555/ecca8f86-a01e-11e5-946b-4e7d7c214860.png)

basically I have a list of languages and categories, plus a list of Brochures that are group by language and category.

could you help me understand what kind of json I would need in order to achieve this, or if it is possible at all?

**Comment by 3lvis** [comment]
@violabg please make a new issue for this.

**Comment by 3lvis** [comment]
@violabg I made a new issue for this https://github.com/hyperoslo/Sync/issues/152
