### ISSUE TITLE
hyp_dateFromISO8601String causes crash

### ISSUE THREAD

**Issue by jkblgithub** [hyperoslo/Sync#141]
I have been testing my app on the simulator on iOS 8.1 and iOS 9.1 without problem, but when I ran it on a device with iOS 9.1, I get a crash caused by hyp_dateFromISO8601String being passed "2015-11-13T09:36:13.184968Z". There are 2 issues here:

1. The crash
2. In situations where the crash does not occur, hyp_dateFromISO8601String returns null for the passed in string, although it is in fact valid iso8601

**Comment by 3lvis** [comment]
I think this is caused because handling of microseconds on ISO dates is not optimal. You'll see that if you remove the microseconds it works.

Made an issue to check this https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/issues/88

**Comment by jkblgithub** [comment]
@3lvis Thanks - We ended up removing the microseconds and it works
