### ISSUE TITLE
Update instead of replace?

### ISSUE THREAD

**Issue by bonebox** [hyperoslo/Sync#144]
Hey @3lvis !

I have a project where I need to add multiple objects of the same entity to Core Data at different times (and retain all of them).  It seems the default behavior of Sync is to delete everything and replace it each time you sync.  For other projects using Sync, I've worked around this by using a predicate along with the new object being sync'd of the kind `"remoteID == %@", newObject.id`.  This will cause the new object to be added if another object with that `id` isn't already found in Core Data.  

This works well for adding new objects, however, the problem I'm encountering is when the object already exists in Core Data. Apparently, Sync is deleting it and re-adding it.  This is a problem in my case, because the objects in question are set as a relationship with another entity in Core Data whose objects are created at a separate time (and not by Sync) and then get linked up.  So obviously, when Sync deletes the object and re-adds it, it breaks this relationship.  

It seems a nicer solution would be instead of deleting and replacing, if any existing object is found in Core Data with a matching primary key as the one you are trying to sync, to just update its attribute values instead of deleting and replacing the entire object.  

The way RestKit handled this was if it found a matching primary key, it just ignored the object completely unless you also set a property that told it which specific keys to inspect for changes between the matching objects. If that key(s) had changed, it updated the existing object's attributes.  Of course, RestKit also just added new objects by default (if the primary key didn't already exist) which seems like a better desired behavior than deleting everything each time.  

So I'm not sure what the best way would be to implement this in Sync, but it would be great to have.  For now, I'm considering just keeping the objects unlinked, and carry an additional attribute in one of them that stores the unique key of the other. Of course, I don't prefer this approach since it requires doing an additional fetch to retrieve the referenced object. Thoughts?

**Comment by bonebox** [comment]
Actually, I just thought of a much simpler solution--after retrieving the JSON and before running Sync, do my own fetch to determine if the object already exists and if so, just don't run Sync.  This works in my case, since the attribute values never change for the same object.  This wouldn't work of course if an object's attributes can potentially change on the server.

**Comment by 3lvis** [comment]
Hi @bonebox,

This certainly looks like a bug, in `Sync` if the object is in the JSON and in Core Data, it should be updated. If it's in the JSON and not in Core Data is inserted. Finally if it's in Core Data and not in the JSON then it's deleted.

Same should be for relationships. Would you mind sharing some details on how I can reproduce this issue so I can ensure we get the desired behaviour? Thanks a lot for your help :heart:

**Comment by 3lvis** [comment]
Also if an object is updated but the values are the same as before then the object doesn't get updated at all.

https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/blob/master/Source/NSManagedObject%2BHYPPropertyMapper.m#L33-L36

**Comment by bonebox** [comment]
Hmm, the object I am testing with is definitely getting deleted each time and it's the same object.    The only thing I can think of is I am comparing date attributes in the predicate (that is also the primary key).  Below is what my code looks like for the predicate (`saveTimestamp` is set as a date attribute in Core Data).  Could that be causing some issue?

```
let timestamp = JSON["saveTimestamp"] as! String
let saveDate = NSDate.hyp_dateFromISO8601String(timestamp)!
let predicate = NSPredicate(format: "saveTimestamp == %@", saveDate)
```

**Comment by bonebox** [comment]
> Finally if it's in Core Data and not in the JSON then it's deleted.

Perhaps this is what's happening?  It's not seeing it as a match so the current object is being deleted, and the new inserted?

**Comment by 3lvis** [comment]
@bonebox that could be. Both items need to have the same `remoteID` in order to be considered the same.

**Comment by bonebox** [comment]
I am setting the `saveTimestamp` attribute as the primary key using `hyper.isPrimaryKey`, so wouldn't it be treated as such?

**Comment by 3lvis** [comment]
sure, although `NSDate` doesn't seem like the best primary key since a slightly millisecond change or timezone change would cause your objects to think they are not unique.

**Comment by bonebox** [comment]
True, although in my case this is fine, since if the date changes at all it means the object has been updated on the server and thus I want a new entry in Core Data.  Also, the server object has no other unique attributes to use as a primary key.

**Comment by 3lvis** [comment]
Do you have an example of the date that you're getting from the backend? Miliseconds could make the entire difference between dates.

**Comment by bonebox** [comment]
Yes, I'm feeding it dummy JSON at the moment, so the date never changes for my testing. It is always `2015-10-07T22:39:49.585Z`.  After passing it to `NSDate.hyp_dateFromISO8601String` the NSDate output is `2015-10-07 22:39:49 +0000`.  This matches what's already in Core Data.

**Comment by 3lvis** [comment]
I wish we could figure out a way to reproduce this bug, it's not happening on my unit tests.

**Comment by 3lvis** [comment]
Hi @bonebox, by any chance is this new behaviour (meaning that it was working before) or is the first time you find the issue.

**Comment by bonebox** [comment]
@3lvis well this is a new project, so it was doing this from the beginning with the latest version of Sync.

**Comment by 3lvis** [comment]
@bonebox Thanks! And congrats on the new project :tada:

**Comment by 3lvis** [comment]
Related to https://github.com/hyperoslo/Sync/issues/162

**Comment by 3lvis** [comment]
Working on a way to specify Sync operations. https://github.com/hyperoslo/Sync/pull/223
