### ISSUE TITLE
Looks like Smart-updates not working

### ISSUE THREAD

**Issue by f1nality** [hyperoslo/Sync#145]
Hello,
I'm using Sync to update my managedobjects.
I retrieve 1000 objects from my api and use Sync.changes to update objects. Though there are absolutely no changes since last fetch 200+ objects are being refreshed (from NSManagedObjectContextObjectsDidChangeNotificationt). 

NSFetchedResultsControllers also update the whole collectionview as number of updates is rather big.

As a result I get collectionview.reloadData though no changes have been made.

By the way, logging is not working the same way as in README:
```swift
    func changeNotification(notification: NSNotification) {
        NSLog("Updated: \(notification.userInfo?[NSUpdatedObjectsKey])") // =nil
        NSLog("Deleted: \(notification.userInfo?[NSDeletedObjectsKey])") // =nil
        NSLog("Inserted: \(notification.userInfo?[NSInsertedObjectsKey])") // =nil
    }
```
```
userInfo	__NSDictionaryM *	2 key/value pairs	0x00007fb2b09e8460
[0]	(null)	"refreshed" : 280 objects	
[1]	(null)	"managedObjectContext" : (no summary)	
```

I'm using swift and tvOS

**Comment by 3lvis** [comment]
@f1nality Hi Denis,

I tried the AppNet demo (I also added logging to that Demo).

You can try it with `pod try Sync` on your terminal.

The things that you have mentioned work without problems. Also logging works fine.

<img width="1177" alt="screen shot 2015-11-22 at 13 33 33" src="https://cloud.githubusercontent.com/assets/1088217/11323789/a71d990c-911d-11e5-8290-baba2aa06d6d.png">

**Comment by 3lvis** [comment]
@f1nality I think the issue might be due the mapping between your Core Data model and your JSON.

Do you have `id` in your JSON and `remoteID` in your Core Data model? Could you share an screenshot of your Core Data relationship and an example of your JSON?

**Comment by f1nality** [comment]
I have noticed that when I have used Sync.changes with predicate logging started to contain "inserted" key with lots of entries (400+) though it should containt "update" key. When I use Sync.changes without predicate only "refreshed" key is being logged.

Yes, I have id and remoteID fields.
Here is my data:

<img width="557" alt="models" src="https://cloud.githubusercontent.com/assets/1628232/11323852/34754ebe-9130-11e5-844d-6fc0b33b8761.png">

<img width="906" alt="json" src="https://cloud.githubusercontent.com/assets/1628232/11323850/2e978af2-9130-11e5-9991-8ea67896c402.png">

**Comment by f1nality** [comment]
By the way, my remoteID is Integer32 (in comparison to demo)

**Comment by 3lvis** [comment]
How does your Sync method looks like? Would be nice to see how does the predicate looks like :)

**Comment by f1nality** [comment]
```swift
        let predicate = NSPredicate(format: "online == true")
        Alamofire.request(Method.GET, URL).responseJSON { response in
            if let channels = response.result.value?["results"] as? [AnyObject] where response.result.isSuccess {
//                Sync.changes(channels, inEntityNamed: "Channel", predicate: predicate, dataStack: dataStack, completion: nil)
                Sync.changes(channels, inEntityNamed: "Channel", dataStack: dataStack, completion: nil)
            }
        }
```

**Comment by 3lvis** [comment]
@f1nality Could you try un-commenting the following lines in your local copy of Sync?

https://github.com/hyperoslo/Sync/blob/master/Source/Sync.m#L90-L98

**Comment by f1nality** [comment]
Now it crashes:

```
2015-11-22 16:10:17.218 my_app[93724:5917983] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSCFSet: 0x7fba48d23b80> was mutated while being enumerated.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010dfd80b5 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010d6dfdeb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010dfd7a14 __NSFastEnumerationMutationHandler + 132
	3   CoreData                            0x000000010dc388c4 -[NSManagedObjectContext executeFetchRequest:error:] + 2932
	4   Sync                                0x000000010cb7b1df +[NSManagedObject(Sync) sync_safeObjectInContext:entityName:remoteID:parent:parentRelationshipName:error:] + 543
	5   Sync                                0x000000010cb7c7fb -[NSManagedObject(Sync) sync_processToOneRelationship:usingDictionary:andParent:dataStack:error:] + 1035
	6   Sync                                0x000000010cb7b9fd -[NSManagedObject(Sync) sync_processRelationshipsUsingDictionary:andParent:dataStack:error:] + 1277
	7   Sync                                0x000000010cb7a536 -[NSArray(Sync) preprocessForEntityNamed:usingPredicate:parent:dataStack:] + 1206
	8   Sync                                0x000000010cb7dbd2 +[Sync changes:inEntityNamed:predicate:parent:inContext:dataStack:completion:] + 1378
	9   Sync                                0x000000010cb7cea9 __61+[Sync changes:inEntityNamed:predicate:dataStack:completion:]_block_invoke + 121
	10  DATAStack                           0x000000010caaa16f _TTRXFdCb_dCSo22NSManagedObjectContext_dT__XFo_oS__dT__ + 31
	11  DATAStack                           0x000000010caaa12f _TFFC9DATAStack9DATAStack29performInNewBackgroundContextFS0_FFT17backgroundContextCSo22NSManagedObjectContext_T_T_U_FT_T_ + 63
	12  DATAStack                           0x000000010caaa0e7 _TTRXFo__dT__XFdCb__dT__ + 39
	13  CoreData                            0x000000010dc7e997 developerSubmittedBlockToNSManagedObjectContextPerform + 199
	14  libdispatch.dylib                   0x0000000110eaf49b _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x0000000110e958ec _dispatch_queue_drain + 2215
	16  libdispatch.dylib                   0x0000000110e94e0d _dispatch_queue_invoke + 601
	17  libdispatch.dylib                   0x0000000110e97a56 _dispatch_root_queue_drain + 1420
	18  libdispatch.dylib                   0x0000000110e974c5 _dispatch_worker_thread3 + 111
	19  libsystem_pthread.dylib             0x00000001111e04f2 _pthread_wqthread + 1129
	20  libsystem_pthread.dylib             0x00000001111de375 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by f1nality** [comment]
where is it checked whether model should be updated or not (is it changed or not)?

**Comment by f1nality** [comment]
hmm, when I try to manually update one object everything ok

```swift
            let predicate = NSPredicate(format: "self == %@", channel)
            
            Sync.changes([["id": channel.remoteID, "liked": !channel.liked.boolValue]], inEntityNamed: "Channel", predicate: predicate, dataStack: dataStack)  { (error: NSError!) -> Void in
                self.updateLikeButton()
            }
```

But when I fetch from api - i get inserts instead of refresh

**Comment by 3lvis** [comment]
> But when I fetch from api - i get inserts instead of refresh

This sentence sounds similar to this other issue. https://github.com/hyperoslo/Sync/issues/144

I'll use your example to check what's going on. Thanks :heart:

**Comment by f1nality** [comment]
Yes, very similar. Looks like old object is being deleted and inserted again.

**Comment by f1nality** [comment]
@3lvis 
I've noticed strange behavior:
If if specify concrete objects in predicate and try to update them - everything ok.
But if don't provide predicate, all objects are being deleted and only objects I have passed to "changes" argument are created.

**Comment by f1nality** [comment]
This workaround at least works for me as expected (objects are refreshed and not recreated)

```swift
                let predicate = NSPredicate(format: "remoteID IN %@", channels.map() { $0["id"] as! NSNumber })
                Sync.changes(channels, inEntityNamed: "Channel", predicate: predicate, dataStack: dataStack, completion: nil)
```

**Comment by 3lvis** [comment]
>But if don't provide predicate, all objects are being deleted and only objects I have passed to "changes" argument are created.

That sounds like expected Sync behaviour: If the object is in the JSON and in Core Data, it should be updated. If it's in the JSON and not in Core Data is inserted. Finally, if it's in Core Data and not in the JSON then it's deleted.

Using a predicate: Sync fetches the objects from Core Data using the predicate, then it does the same procedure as the one mentioned before but instead of using all the elements in Core Data, it only diffs using the elements that apply to the predicate.

**Comment by f1nality** [comment]
wow, ok then. But if I specify no predicate and pass objects - it also deletes and inserts objects which were in coredata (this was original problem).

By the way, how in this case should api pagination should be implemented using sync? I make requests to api with specified "page" and get only part of data. When I try to sync it - all other pages in core data will be deleted.

**Comment by 3lvis** [comment]
>wow, ok then. But if I specify no predicate and pass objects - it also deletes and inserts objects which were in coredata (this was original problem).

This definitely looks like a bug. I'll have a look when I get some time.

>By the way, how in this case should api pagination should be implemented using sync? I make requests to api with specified "page" and get only part of data. When I try to sync it - all other pages in core data will be deleted.

You'll need to find a way to differentiate objects that belong to each page. Otherwise Sync doesn't have a way to know what got deleted in each page.

**Comment by f1nality** [comment]
> This definitely looks like a bug. I'll have a look when I get some time.

I have found out that I was wrong about reason of this bug, it's not about predicate. This happened because I made simultaneous requests that fetched the same data. As a result sync added duplicates (but shouldn't?) and possible has broken something in db. After that this delete/insert operations happens after every request (even with predicate and without it). Only db clearing helps.
What it interesting, duplicates disappear from collectionview after few more requests, but delete/insert operations happens after each request until I clear my db and stop making simultaneous requests with th same data.

> You'll need to find a way to differentiate objects that belong to each page (this is why the predicate is needed). Otherwise Sync doesn't have a way to know what got deleted in each page.

It would be great if it can be customizable, don't you think? Not to delete objects which are not in `changes` I mean. Deleting happens in DATAFilter, am I right?

**Comment by 3lvis** [comment]
@f1nality so you have been calling `sync.changes` multiple times? sometimes before it has even finished? That should definitely cause duplicates.

Duplicates get deleted because we have a method that clears duplicates. If there's two objects with the same `remoteID` (primary key) those items get deleted.

https://github.com/3lvis/DATAObjectIDs/blob/master/Source/DATAObjectIDs.m#L39-L47

**Comment by f1nality** [comment]
@f1nality yes. Looks like duplicates are being deleted after later requests, but something still stays broken and I begin to receive delete/insert notifications on data which hasn't changed.

> It would be great if it can be customizable, don't you think? Not to delete objects which are not in changes I mean. Deleting happens in DATAFilter, am I right?

This is not about this issue's problem - I mean it would be nice if I can turn off deleting of objects in core data which was not present in API request response. e.x. `Sync.changes(data, inEntityNamed: "Model", dataStack: dataStack, completion: nil, deleteNonexistent: false)`

**Comment by 3lvis** [comment]
If you were using something like that, how would you delete non existing items then? What happens if items get deleted from your backend?

**Comment by f1nality** [comment]
1. I add `deleted' boolean property. Than I can manually delete them in core data by this field, or just hide them and not delete at all (its often useful not to really delete objects as they may be deleted occasionally or something else).
2. More often I don't need ability to delete at all

**Comment by rafalwojcik** [comment]
@f1nality Look at my response in #162

**Comment by 3lvis** [comment]
Related to https://github.com/hyperoslo/Sync/issues/162

**Comment by 3lvis** [comment]
Working on a way to specify Sync operations. https://github.com/hyperoslo/Sync/pull/223
