### ISSUE TITLE
Syncing an object twice in a short time yields duplicates

### ISSUE THREAD

**Issue by antonholmquist** [hyperoslo/Sync#146]
Since each sync is done on a separate context in a separate thread they are run in pararell. This creates a race condition where each context will not know about the other context inserting the same object at the same time.

I quick fixed this by using a single background context for every `performInNewBackgroundContext` call.

**Comment by 3lvis** [comment]
@antonholmquist This is correct, syncing the same resource isn't safe. I think this is related to #93.

When I have many Syncing methods I usually chain them so one doesn't start before the other one. Having NSOperation support would work great too.

**Comment by antonholmquist** [comment]
Thanks. But don't you think this should be handled by the library? It can sometimes be tricky to know if other parts of your app is syncing simultaneously, but it is pretty easy to enforce in the library.

**Comment by 3lvis** [comment]
@antonholmquist you're right, would be great if we could handle this internally. Any ideas? So far I only could come up with the NSOperation way.

**Comment by antonholmquist** [comment]
My quickfix was just to rewrite the `performInNewBackgroundContext:` method to use a single context instead of a new one each time. It makes the blocks performed by the context run synchronously.

```
var backgroundContext : NSManagedObjectContext!

public func performInNewBackgroundContext(operation: (backgroundContext: NSManagedObjectContext) -> ()) {
    
    if (backgroundContext == nil) {
        backgroundContext = NSManagedObjectContext(concurrencyType: DATAStack.backgroundConcurrencyType())
        backgroundContext.persistentStoreCoordinator = self.persistentStoreCoordinator
        backgroundContext.undoManager = nil
        backgroundContext.mergePolicy = NSMergeByPropertyStoreTrumpMergePolicy
        
        NSNotificationCenter.defaultCenter().addObserver(self, selector: "backgroundContextDidSave:", name: NSManagedObjectContextDidSaveNotification, object: backgroundContext)
    }
    
    let context = backgroundContext!
    
    let contextBlock: @convention(block) () -> Void = {
        operation(backgroundContext: context)
    }
    
    let blockObject : AnyObject = unsafeBitCast(contextBlock, AnyObject.self)
    context.performSelector(DATAStack.performSelectorForBackgroundContext(), withObject: blockObject)
}
```

**Comment by 3lvis** [comment]
@antonholmquist Hi Anton,

Interesting workaround, I remember having a shared backgroundContext before, but Core Data is *very* fragile. Sharing managed object contexts means even more shared state. I would prefer to keep this as it is. I have checked other "Core data wrappers" for example the [Big Nerd Ranch](https://github.com/bignerdranch/CoreDataStack#-creating-a-worker-context) one and they do something similar, and I think it's because is more safe. I would love to share more details on where exactly having a shared background context causes more harm than gains but at the moment I can't come up with anything concrete.

**Comment by antonholmquist** [comment]
I would actually argue that a backgroundContext should be more stable! Having multiple contextes, each on its own thread, syncing in pararell introduces both a risk for duplicates (which we saw here) as well as potential merge conflicts. 

Yes, having sync operations as NSOperations could pretty much solve the same issue. As would using a single background dispatch queue for all sync code. It's all about avoiding sync operations running in pararell.

**Comment by 3lvis** [comment]
I agree, changing the behaviour of background contexts sounds more like a workaround to me. If we add NSOperation support we'll be killing two birds in one store since we would also be able to cancel Sync operations https://github.com/hyperoslo/Sync/issues/93
