### ISSUE TITLE
Add ability to sync object with custom property names

### ISSUE THREAD

**Issue by kostiakoval** [hyperoslo/Sync#15]
![screen shot 2015-03-03 at 09 51 39](https://cloud.githubusercontent.com/assets/1086260/6459048/eb1bba20-c18a-11e4-9344-dd6a17d13577.png)
I would like to be able sync JSON to this Person object with custom properties names
children ->> Person (to many of type Person) 
parents ->> Person (to many of type Person)

**Comment by NSElvis** [comment]
So a `child` has many `parents` (but it's a person) and a `parent` has many `childs` (he's also a person).

How would you represent this on a JSON? Something like this?

```json
{
  "id":0,
  "name":"Parent name 0",
  "children":[
    {
      "id":1,
      "name":"Child name 0"
    },
    {
      "id":2,
      "name":"Child name 1"
    }
  ]
}
```

**Comment by kostiakoval** [comment]
yes like that + parents, similar to children
```
{
  "id":0,
  "name":"Parent name 0",
  "children":[
    {
      "id":1,
      "name":"Child name 0"
    },
    {
      "id":2,
      "name":"Child name 1"
    }
  ],
  parents":[
    {
      "id":3,
      "name":"Mom"
    },
    {
      "id":4,
      "name":"Dad"
    }
  ]
}
```

**Comment by NSElvis** [comment]
@kostiakoval Thanks :) I'll take a look

**Comment by kostiakoval** [comment]
I mean it's always nice to give declarative names for properties like parents, children, etc not just it should be the same as Entity name

**Comment by NSElvis** [comment]
Totally agree :+1:

**Comment by kostiakoval** [comment]
This one should be working now with latest fix

**Comment by NSElvis** [comment]
Awesome!

**Comment by kostiakoval** [comment]
I would prefer to ass test maybe for that?
