### ISSUE TITLE
Sync to-many relationships only providing an array of ids

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Sync#151]
In https://github.com/hyperoslo/Sync/issues/140 we added syncing to-one relationships by only providing the id, this is standard in frameworks like Ruby on Rails, but for consistency would be nice if we also supported sending an array the ids for to-many relationships.

For example instead of:

```json
[
  {
    "id": 6,
    "name": "Shawn Merrill",
    "notes": [
      {
        "id": 0,
        "text": "Shawn Merril's diary, episode 1",
      }
    ]
  }
]
```

You would need:

```json
[
  {
    "id": 6,
    "name": "Shawn Merrill",
    "notes_ids": [0, 1, 2]
  }
]
```

**Comment by wainglaister** [comment]
The name of the array should also be configurable with `hyper.remoteKey`.

**Comment by adrienjt** [comment]
"3lvis self-assigned this 2 days ago"
Very much looking forward to it!

**Comment by 3lvis** [comment]
@adrienjt Thanks for writing, haha, if you didn't said anything this would probably wouldn't have been done.
