### ISSUE TITLE
JSON Help

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Sync#152]
Thanks for the reply.

I can't figure it out the way to structure my json in order to be converted to my model.

![screen shot 2015-12-11 at 15 48 37](https://cloud.githubusercontent.com/assets/3963176/11746555/ecca8f86-a01e-11e5-946b-4e7d7c214860.png)

basically I have a list of languages and categories, plus a list of Brochures that are group by language and category.

could you help me understand what kind of json I would need in order to achieve this, or if it is possible at all?

By @violabg

**Comment by 3lvis** [comment]
Hi @violabg.

First of all, change the `id` for `remoteID`.

**Comment by 3lvis** [comment]
if your JSON is a list of brochures then you need something like this:

```json
[
  {
    "id": 0,
    "is_current":..,
    "is_local":..,
    "is_new":..,
    "modification_date":..,
    "name":..,
    "needs_update":..,
    "sort_id":..,
    "thumb":..,
    "url":..
    "category": {
      "id":..,
      "name":..,
      "sort_id":..,
      "thumb":..
    },
    "language": {
      "id":..,
      "name":..
    }
  }
]
```

**Comment by violabg** [comment]
Thanks 3lvis,

I thought so, but I have a problem with that.
you see the property thumb for category? that is an image (binary data).
I have maybe 500/800 brochures and only 10/15 categories and I don't want to repeat the same category (including thumb) for 500/800 times.

that is why I was looking at
Sync relationships by only providing the id #140

**Comment by 3lvis** [comment]
@violabg I see, if you have all the categories synced then you can do:

if your JSON is a list of brochures then you need something like this:

```json
[
  {
    "id": 0,
    "is_current":..,
    "is_local":..,
    "is_new":..,
    "modification_date":..,
    "name":..,
    "needs_update":..,
    "sort_id":..,
    "thumb":..,
    "url":..
    "category_id":..,
    "language": {
      "id":..,
      "name":..
    }
  }
]
```

**Comment by 3lvis** [comment]
You need to separate the syncing of categories and languages first. Then you should do the brochures syncing.

**Comment by violabg** [comment]
thanks, is working

**Comment by 3lvis** [comment]
Great!

**Comment by violabg** [comment]
I'm using your AppNet sample as a test base for may data and syncing the data this way:

```swift
func fetchItems(completion: (NSError?) -> Void) {

        if let urlAppNet = NSURL(string: AppNetURL) {
            let request = NSURLRequest(URL: urlAppNet)
            let operationQueue = NSOperationQueue()

            NSURLConnection.sendAsynchronousRequest(request, queue: operationQueue) { [unowned self] _, data, error in
                if let data = data, json = (try? NSJSONSerialization.JSONObjectWithData(data,
                    options: NSJSONReadingOptions.MutableContainers)) as? Dictionary<String, AnyObject> {
                        Sync.changes(json["languages"] as! Array,
                            inEntityNamed: "Language",
                            dataStack: self.dataStack,
                            completion: { error in
                                self.syncCategories(json)
                        })
                } else {
                    completion(error)
                }
            }
        }
    }
    
    func syncCategories(json:Dictionary<String, AnyObject>) {
        Sync.changes(json["categories"] as! Array,
            inEntityNamed: "PdfCategory",
            dataStack: self.dataStack,
            completion: { error in
                self.syncBrochures(json)
        })
    }
    
    func syncBrochures(json:Dictionary<String, AnyObject>) {
        Sync.changes(json["brochures"] as! Array,
            inEntityNamed: "Brochure",
            dataStack: self.dataStack,
            completion: { error in
                print("syncBrochures")
        })
    }
```

do you think is the correct way=

**Comment by 3lvis** [comment]
@violabg What do you mean? Are you getting errors?

**Comment by violabg** [comment]
No errors, since you said "if you have all the categories and languages synced then you can do

```json
[
  {
    "id": 0,
    "is_current":..,
    "is_local":..,
    "is_new":..,
    "modification_date":..,
    "name":..,
    "needs_update":..,
    "sort_id":..,
    "thumb":..,
    "url":..
    "category_id":..,
    "language_id":...
  }
]
```

I was wondering if doing it on the same json fetch on each completion block was the appropriate way to do it.

**Comment by violabg** [comment]
Actually I'm getting some problems, related to notifications, when the json changes I'm getting correct notification only from the language entity, while for PdfCategory and Brochure I'm only getting inserted notification, (the core data always get updated). it is similar to issue #153.

For me it is important to keep track of changes from one json to another one, since I have to do some clean up, especially for the entities been deleted.

Is there another way to keep track of deleted entities between syncs, other the trough notifications?

**Comment by 3lvis** [comment]
@violabg lets keep the conversation on #153 :)
