### ISSUE TITLE
Use hyper.remoteKey (or something similar) for setting the key thats provided to sync the relationship.

### ISSUE THREAD

**Issue by doohoo** [hyperoslo/Sync#158]
Hello.

Nice feature update of the relationship syncing provided by only the ID.
However.. currently the `keyName` is created from the entity name + `_id`. (Right me if im wrong :), im just looking at https://github.com/hyperoslo/Sync/pull/147/files)
Is there a way to set it to something else? 
Lets say the API you are currently working with are returning the relationship id like this: `categoryID`.

Would `hyper.remoteKey = "categoryID"` or something similar to this work?

**Comment by 3lvis** [comment]
@doohoo Hi Doo!

At the moment only `category_id` is supported. 

You could workaround this by modifying your JSON first.

In the future would be nice to add support using `hyper.remoteKey`.
