### ISSUE TITLE
Crash when trying to sync abstract entity.

### ISSUE THREAD

**Issue by galinyonchev** [hyperoslo/Sync#159]
Dear Sync support,

I have the following problem:

I have a Patient object, which has attributes firstName, lastName, email, etc., and measure. This measure is of type NSSet and it is an abstract entity. It splits into three different objects - Alcohol, Fitness and Weight, which inherit Measure. So, for example, the Patient JSON is something like this:

```json
{
  "firstName": "John",
  "lastName": "Malkovic",
  "email": "john@yahoo.com",
  "measure": [
    {
      "beer": 0,
      "object_deleted": 0,
      "long_drink": 0,
      "wine": 0,
      "date": "2015-10-16",
      "object_type": "Alcohol",
      "alcohol_qty": null,
      "short_drink": 0
    },
    {
      "object_deleted": 0,
      "weight": 39.916128557262,
      "object_type": "Weight",
      "date": "2015-10-16"
    }
  ]
}
```

So, what I am trying to do is to sync a JSON file, which contains only measure objects, with my Patient object. Example JSON:

```json
{
  "measure": [
    {
      "beer": 0,
      "object_deleted": 0,
      "long_drink": 0,
      "wine": 0,
      "date": "2015-10-16",
      "object_type": "Alcohol",
      "alcohol_qty": null,
      "short_drink": 0
    },
    {
      "object_deleted": 0,
      "weight": 39.916128557262,
      "object_type": "Weight",
      "date": "2015-10-16"
    }
  ]
}
```

The problem is that my app crashes with the following error:

>> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSDictionary initWithObjects:forKeys:]: count of objects (1) differs from count of keys (0).

Which is in DATAFilter.m file, line 43:

>>    NSDictionary *remoteIDAndChange = [NSDictionary dictionaryWithObjects:changes
                                                                  forKeys:remoteObjectIDs];

Any ideas why this is happening and how to fix it? Is it because the JSON file contains only one object, which is abstract? Or something else?

Thank you in advance!

**Comment by 3lvis** [comment]
@galinyonchev Hi could you share an screenshot of your Core Data model, please? Having the structure is important to see what's going on behind the scenes.

Thanks!

**Comment by galinyonchev** [comment]
Have a look here:

![screen shot 2015-12-17 at 11 52 56](https://cloud.githubusercontent.com/assets/13518877/11866634/0976a472-a4b5-11e5-8f19-782edb4bd3de.png)

**Comment by 3lvis** [comment]
@galinyonchev first of all you're missing the reverse relationship on Measure, with Alcohol, Fitness and Weigth.

<img width="1063" alt="screen shot 2015-12-17 at 12 34 36" src="https://cloud.githubusercontent.com/assets/1088217/11868760/8be7bcfc-a4ba-11e5-92e1-7cf5d4f8cad2.png">

**Comment by 3lvis** [comment]
@galinyonchev first of all you're missing the reverse relationship on Measure, with Alcohol, Fitness and Weight.

<img width="884" alt="screen shot 2015-12-17 at 12 42 22" src="https://cloud.githubusercontent.com/assets/1088217/11868918/a0f3711c-a4bb-11e5-9b70-499e25743e77.png">

**Comment by 3lvis** [comment]
@galinyonchev as you can see in my example, every entity has a primary key. Also, every element needs it's own JSON object.

For your structure, Sync would expect something like this.

```json
[
  {
    "id": 0,
    "text": "Melisa White",
    "measures": [
      {
        "id": 0,
        "baselines": [
          {
            "id": 0,
            "text": "Baseline 1"
          }
        ],
        "alcohols": [
          {
            "id": 0,
            "text": "Alcohol 1",
            "measure": {
              "id": 0,
              "text": "Alcohol Measure 1"
            }
          }
        ],
        "fitnesses": [
          {
            "id": 0,
            "text": "Fitness 1",
            "measure": {
              "id": 0,
              "text": "Fitness Measure 1"
            }
          }
        ],
        "weights": [
          {
            "id": 0,
            "text": "Weight 1",
            "measure": {
              "id": 0,
              "text": "Weight Measure 1"
            }
          }
        ]
      }
    ]
  }
]
```

**Comment by 3lvis** [comment]
The biggest problem here is that Sync doesn't understand `object_type`. So, if you want to use Sync with your same JSON structure, I would recommend you to move all the attributes from Alcohol, Fitness and Weight and move them to the Measure entity, something like this:

<img width="637" alt="screen shot 2015-12-17 at 13 00 11" src="https://cloud.githubusercontent.com/assets/1088217/11869217/3ae4bfd6-a4be-11e5-8a6c-7675f81e3580.png">

**Comment by galinyonchev** [comment]
OK, now I use predicate as you said in your last comment. The problem is that I try to sync my Core Data object (Patient) with JSON that contains only two of patient's attributes - GUID (my primary key) and the measures. It just does not update the Patient object. To make it work I have to add two more attributes and then Sync recognizes it and updates the Patient object. Do you know what is wrong?

For example the Patient object have 10 attributes - first name, last name, email, bla, bla, guid (primary key), measures. JSON looks like this:

>   "guid": "some-guid-here",
  "measure": [
    {
      "beer": 0,
      "object_deleted": 0,
      "long_drink": 0,
      "wine": 0,
      "date": "2015-10-16",
      "object_type": "Alcohol",
      "alcohol_qty": null,
      "short_drink": 0
    },
    {
      "object_deleted": 0,
      "weight": 39.916128557262,
      "object_type": "Weight",
      "date": "2015-10-16"
    }
  ]

This way it does not work. I have to add two more attributes to make it sync and update. Any ideas?

**Comment by 3lvis** [comment]
@galinyonchev What's the primary key of the measure object? Also, wouldn't `measures` be better? Since it's an array.

**Comment by galinyonchev** [comment]
Primary key of measure object is "date". Yes, measures will be better, I will change it.

**Comment by 3lvis** [comment]
If date is the primary key, then in your example, those items will be replaced since both have the same date. I'll have a look at what's going on. I guess the `guid` is the primary key of Patient.

Will try to reproduce your issue and get back to you :) 

This should work just fine.

**Comment by galinyonchev** [comment]
Yes, *guid* is the primary key of *Patient*. 
Primary key of *measure* is *date*.

So, is it a problem that my measure items have the same primary key?

**Comment by 3lvis** [comment]
@galinyonchev of course, primary key needs to be unique.

**Comment by galinyonchev** [comment]
OK, I made the change, now Measure has an attribute "remoteID" which is the PrimaryKey. It still needs 4 attributes in the JSON (measures, guid and two others) to update the Patient object. I have no idea why this is happening... :(
