### ISSUE TITLE
Sync is crashing when syncing children JSON to Object with not existing relationship 

### ISSUE THREAD

**Issue by kostiakoval** [hyperoslo/Sync#16]
I have a Model with many Relationship. In the JSON I have a simpler model without all relationship

When I Sync numbers, it crashes because trying to set Parent `unit` property on Number (unit is relationship to OrganizationUnit, but I don't want to sync organisations here, just numbers) 

Model Example :
![screen shot 2015-03-03 at 09 12 52](https://cloud.githubusercontent.com/assets/1086260/6458597/98829cde-c185-11e4-98c0-11d92f66aca7.png)

JSON Example:
``` json
[{
  "id": 1,
  "number": 10.0,
  "numberType": 0,
  "children" : [
    {
      "id": 2,
      "number": 11.0,
      "numberType": 0
    },
    {
      "id": 3,
      "number": 12.0,
      "numberType": 0,
    }
  ]
}]
```

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unacceptable type of value for to-one relationship: property = "unit"; desired type = REMAOrganizationUnit; given type = REMANumber; value = <REMANumber: 0x7aeac650> 

It crash here :)
![screen shot 2015-03-03 at 10 11 21](https://cloud.githubusercontent.com/assets/1086260/6459295/ab3b53d6-c18d-11e4-84db-2b453eaa2906.png)

it has a relationship with name `unit` that point to parent organization, but there is no organization in the JOSN and I don't want to process it

**Comment by kostiakoval** [comment]
It was hard to describe that problem :(

**Comment by NSElvis** [comment]
@kostiakoval thanks for adding the JSON and the model, both help a lot to reproduce the issue. Maybe this should be a requirement in our contribution guidelines.

You are *awesome* :star2:
