### ISSUE TITLE
Examples with Alamofire

### ISSUE THREAD

**Issue by iroller** [hyperoslo/Sync#164]
A few examples on using Sync with Alamofire would be very useful.

Thanks for all the work Sync btw. Just started to use it and love it.

**Comment by defal7** [comment]
I'll do this for you and chuck a pull request up this evening for you @iroller

**Comment by 3lvis** [comment]
@defal7 Probably you could update the [AppNet](https://github.com/hyperoslo/Sync/tree/master/AppNet) demo to use Alamofire.

**Comment by 3lvis** [comment]
Checkout https://github.com/hyperoslo/Sync/tree/master/AppNet
