### ISSUE TITLE
Better error handling for AnyObject being passed in.

### ISSUE THREAD

**Issue by henryhardy** [hyperoslo/Sync#168]
So obviously we can do errors in our completion handler, but i am wondering if anyone has an effective way to do error handing for the data that you actually pass in, or if there is a way for Sync to actually skip to the completion handler and throw an error before it causes a crash.

For example, it would be idea if i could pass in something totally whack like 

Sync.changes(
  changes: "hello how are you?",
  inEntityNamed: String!,
  dataStack: DATAStack!,
  completion: ((NSError!) -> Void)!)

and have it just throw an error as opposed to crashing and burning horribly. Does anyone have any method they currently use to achieve this?

**Comment by 3lvis** [comment]
Hi Henry!

I have a fix for this, we can use Swift's better type system to enforce the right type in this cases.

**Comment by 3lvis** [comment]
Hi @henryhardy,

I rewrote some parts of Sync in Swift and type safety is now 93,56% better! For example now it's very clear that the `changes` part requires an array of dictionaries.

https://github.com/hyperoslo/Sync/blob/master/Source/Sync.swift#L8
