### ISSUE TITLE
Sync.changes is freezing main thread

### ISSUE THREAD

**Issue by GlaucoNeves** [hyperoslo/Sync#177]
Hi, first of all, thanks for the great library!

I'm using Sync to synchronize an array with more than 10.000 entries. While I was debugging the code I saw the code is taking about 2 minutes to create the entities from JSON, running in background, that's ok. But after that, when the Sync code calls the context.save() my GUI freezes for about 45 seconds. I notice context.save() runs in background, but it seems self.mainContext.performSelector has some running condition causing the freeze.

I don't know if I made myself clear, feel free to ask more details.

**Comment by 3lvis** [comment]
Hi @GlaucoNeves,

Thanks for reporting this. I'll see what we can do but I can't promise so much since it could be an edge case.

Do you have any possible solutions in mind?

Best,

**Comment by GlaucoNeves** [comment]
Hi @3lvis 

I had to go with an in house solutions, the limitations I had with Sync were:
- We use paginated request, but we don't have the identification inside each page, so we didn't find a way to not lose the objects from Core Data that weren't in that page.
- There wasn't a mechanism to detect duplicates inside the json.
- We have more than one property that composes the 'primary key'
- And the freeze time.

To solve the GUI freeze I used another Core Data Stack model. To make the background operations I created a backgroundContext with the same persistentStore as my main context, and instead of merge contexts I send a notification saying the new data is in the persistentStore, and then the responsibility goes to the controller to refetch and refresh the view. I don't know if this approach could work for you.

Once more, great work, your library served as an inspiration. Congrats!

**Comment by 3lvis** [comment]
Thanks @GlaucoNeves!

**Comment by rafalwojcik** [comment]
@GlaucoNeves to prevent deleting objects you can do swizzling like this:
`import Foundation
import CoreData
import DATAFilter

extension DATAFilter {

    override public class func initialize() {
        struct Static {
            static var token: dispatch_once_t = 0
        }
        dispatch_once(&Static.token) {
            let originalSelector = #selector(DATAFilter.changes(_:inEntityNamed:predicate:operations:localKey:remoteKey:context:inserted:updated:))
            let swizzledSelector = #selector(DATAFilter.swizzled_changes(_:inEntityNamed:predicate:operations:localKey:remoteKey:context:inserted:updated:))
            let originalMethod = class_getClassMethod(self, originalSelector)
            let swizzledMethod = class_getClassMethod(self, swizzledSelector)
            method_exchangeImplementations(originalMethod, swizzledMethod)
        }
    }

    class func swizzled_changes(changes: [AnyObject]!, inEntityNamed entityName: String!, predicate: NSPredicate!, operations: DATAFilterOperation, localKey: String!, remoteKey: String!, context: NSManagedObjectContext!, inserted: (([NSObject : AnyObject]!) -> Void)!, updated: (([NSObject : AnyObject]!, NSManagedObject!) -> Void)!) {
        DATAFilter.swizzled_changes(changes, inEntityNamed: entityName, predicate: predicate, operations: [.Insert, .Update], localKey: localKey, remoteKey: remoteKey, context: context, inserted: inserted, updated: updated)
    }
}`

**Comment by 3lvis** [comment]
@GlaucoNeves Hi Glauco, I have been investigating performance issues with saving things and have create a sample project where I'm syncing more than 60 000 objects and I have found the freeze when merging the background objects with the main context. I'm looking for different ways to fix this but so far your suggestion seems like it would be a good candidate, meaning, sending a notification to the UI for fetching instead of merging items to the main context seems like something it could work.

Thanks again for your time and suggestions.

**Comment by 3lvis** [comment]
Check https://github.com/hyperoslo/Sync/pull/249
