### ISSUE TITLE
Relationship mapping chooses the wrong relationship

### ISSUE THREAD

**Issue by wainglaister** [hyperoslo/Sync#179]
Consider 2 entities each having 2 bi-directional relationships to each other. For instance, a route with a start and end location. The relationship mapping in `NSManagedObject+Sync` uses `relationships.first` to choose the destination and determine the key. In this case the same object will be mapped into the start and end relationships.

**Comment by 3lvis** [comment]
I guess this is related to https://github.com/hyperoslo/Sync/pull/180

Great work, @wainglaister! 

Thanks a lot :bouquet:
