### ISSUE TITLE
Progress Information

### ISSUE THREAD

**Issue by wh33ler** [hyperoslo/Sync#182]
Would it be possible to add progress information to the sync changes call? I have a lot of Sync parts that take very long and would like to show the current progress to the user. Is this even possible to build in?

**Comment by tommypeps** [comment]
NSProgress
https://developer.apple.com/library/prerelease/ios/documentation/Foundation/Reference/NSProgress_Class/index.html

**Comment by 3lvis** [comment]
Hi @wh33ler,

We don't have anything like what you mention built-in.

Right now you could use notification changes to let the user know how many items have being updated/deleted or inserted.

https://github.com/hyperoslo/Sync#logging-changes

If you plan to work on this, you might want to consider using notifications for this.

**Comment by 3lvis** [comment]
Closing for lack of response.
