### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by szwicker** [hyperoslo/Sync#183]
Will you provide Carthage support in the future?

**Comment by 3lvis** [comment]
Hi @szwicker,

I'm afraid this could take some time since all the dependencies would have to have Carthage support too. But please, feel free to add that if you want it (in a PR). I'll take some time to maintain it in the future if you get this done.

Thanks a lot!

**Comment by 3lvis** [comment]
Added Carthage support on the latest version.
