### ISSUE TITLE
Predicate on child entity

### ISSUE THREAD

**Issue by macfurin** [hyperoslo/Sync#184]
Consider 2 entities having one-to-many relationship (Plan <-->> Workout).
How to proceed to sync only workouts with distance nil in Core Data ? I cannot specify a predicate on Workout (just ANY workouts.distance = nil on Plan) and in this case all workouts are synced.
I also tried to sync Plan first and then Workout (with `plan_id` ) without success
```json
{
   "plan":[
      {
         "id":"1",
         "name":"Marathon",
         "workouts":[
            {
               "id":"1",
               "week":1,
               "day":1,
               "name":"Easy run",
               "distance":""
            }
         ]
      }
   ]
}
```

**Comment by 3lvis** [comment]
Hi @macfurin, can I have a look at your Core Data model, please?

I'll look into an example on Syncing only workouts with `nil` distance. To be clear, you are saying, taking this JSON, only update workouts in Core Data that have nil distance, right?

**Comment by macfurin** [comment]
Hi @3lvis, there my model : 
![capture d ecran 2016-03-04 a 13 54 09](https://cloud.githubusercontent.com/assets/1177619/13527627/b2c95950-e210-11e5-83ca-8e279e8152c0.png)
I'm trying to sync Plan and only workouts with `nil` distance. I don't want those with distance being deleted or updated because this ones are completed and should not change.

**Comment by 3lvis** [comment]
I'm sorry that this took AGES.

This a first approach at syncing what you are asking. Doing this with workout inside plan is going to be more complicated. I know this is not exactly what you asked but I hope is useful for you.

https://github.com/hyperoslo/Sync/pull/194

**Comment by 3lvis** [comment]
Again, sorry for the late response!

**Comment by 3lvis** [comment]
https://github.com/hyperoslo/Sync/pull/194

**Comment by macfurin** [comment]
Thanks 3lvis, I considered this approach and that's good for my needs.
