### ISSUE TITLE
crashing while synching start

### ISSUE THREAD

**Issue by Raghvendra7** [hyperoslo/Sync#185]
I m trying to do as given in demo app but when i tried to sync it crash with error
what the problem with it
Sync.changes(userDataJSON , inEntityNamed: "RMCOrganisation", dataStack: self.dataStack!, completion: { error in
                completion(error)
            })

gettting error

'NSInvalidArgumentException', reason: 'Invalid keypath  passed to setPropertiesToFetch:

**Comment by 3lvis** [comment]
Hi @Raghvendra7, 

Could I get a peek at your Core Data model and an example of your JSON structure?

**Comment by Raghvendra7** [comment]
![screen shot 2016-03-03 at 6 07 08 pm](https://cloud.githubusercontent.com/assets/10459999/13494534/db8df0ae-e16a-11e5-81da-09af1e1ef6d0.png)


my json response is

rmcorganization: [
{
id: "41da96ba-e818-7edf-7658-e26ec2a91600",
name: "Find My Employee Staging",
web_url: "http%3A%2F%2Fraremediacompany.in%2F",
domainName: "findmyemployeestaging",
rmcobject: "rmcorganization",
rmcphoto: {
thumbnailUrl: null,
photoUrl: null,
orgUrl: null
},
address: "G-84, Connaught Place New Delhi -110001",
updated: "2016-02-26T06:02:49+05:30",
rmcosd: [
{},
{
rmcservice: [],
name: "Version Code And Name",
object: [
"rmccheckin"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "User State",
object: [
"rmccheckin"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "User Type",
object: [
"rmcdevice",
"rmccheckin"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "Activation Code",
object: [
"rmcperson",
"rmcdevice",
"rmccheckin"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "User Name",
object: [
"rmcdevice",
"rmccheckin"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "Location Address",
object: [
"rmccheckin"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "App Anlaytics",
object: [
"rmcdevice",
"rmccheckin"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "App Analytics",
object: [
"rmcdevice",
"rmccheckin"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "Password",
object: [
"rmcperson"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "PhotoUrl",
object: [
"rmcperson"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "Email",
object: [
"rmcdevice",
"rmccheckin"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "IMEI",
object: [
"rmcthing"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "Activated Activation Code",
object: [
"rmcperson"
]
},
{
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a"
}
],
name: "Battery Percentage",
object: [
"rmccheckin"
]
}
],
rmcservice: [
{
id: "8574eca3-1d30-9d95-bdd2-a73812ff796a",
rmcssd: []
}
]
}

**Comment by Raghvendra7** [comment]
what should i do what my mistake

**Comment by 3lvis** [comment]
I had to convert your JSON to valid JSON first. I'll check now :)

```json
{
   "rmcorganization":[
      {
         "id":"41da96ba-e818-7edf-7658-e26ec2a91600",
         "name":"Find My Employee Staging",
         "web_url":"http%3A%2F%2Fraremediacompany.in%2F",
         "domainName":"findmyemployeestaging",
         "rmcobject":"rmcorganization",
         "rmcphoto":{
            "thumbnailUrl":null,
            "photoUrl":null,
            "orgUrl":null
         },
         "address":"G-84, Connaught Place New Delhi -110001",
         "updated":"2016-02-26T06:02:49+05:30",
         "rmcosd":[
            {
               "rmcservice":[
                  {
                     "id":"8574eca3-1d30-9d95-bdd2-a73812ff796a"
                  }
               ],
               "name":"User State",
               "object":[
                  "rmccheckin"
               ]
            }
         ],
         "rmcservice":[
            {
               "id":"8574eca3-1d30-9d95-bdd2-a73812ff796a",
               "rmcssd":[

               ]
            }
         ]
      }
   ]
}
```

**Comment by 3lvis** [comment]
Added an example here https://github.com/hyperoslo/Sync/pull/188
