### ISSUE TITLE
There is an error when I use mapping data 

### ISSUE THREAD

**Issue by alexsanderskywork** [hyperoslo/Sync#192]
I get this error Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSDictionary initWithObjects:forKeys:]: count of objects (439) differs from count of keys (0)

https://www.dropbox.com/s/3kudn65dqxml13v/sync%20error.png?dl=0
https://www.dropbox.com/s/g074ns51yv7c3o0/Screen%20Shot%202016-03-17%20at%208.22.28%20PM.png?dl=0

```
    private func save() {
        guard let jsonPath = bundle.pathForResource("allStations", ofType: "json") else { return }
        guard let jsonData = NSData(contentsOfFile: jsonPath) else { return }
        
        let json = try! NSJSONSerialization.JSONObjectWithData(jsonData, options: .AllowFragments) as! [String : AnyObject]
        
        if let departureCity = json["citiesFrom"] as? [[String: AnyObject]] {
            Sync.changes(departureCity, inEntityNamed: "DepartureCity", dataStack: dataStack) { (error) -> Void in
                if error != nil {
                    print(error?.localizedDescription)
                }
            }
        } else {
            print("there is an error in departureCity")
        }
        
        if let hostCity = json["citiesTo"] as? [[String : AnyObject]] {
            Sync.changes(hostCity, inEntityNamed: "HostCity", dataStack: dataStack) { (error) -> Void in
                if error != nil {
                print(error?.localizedDescription)
                }
            }
        } else {
            print("there is an error in host city")
        }
    }
```

**Comment by alexsanderskywork** [comment]
I changed my model but I am getting this error 
https://www.dropbox.com/s/mppurak0rgqxlc9/newmodel.png?dl=0

**Comment by 3lvis** [comment]
Hi @alexsanderskywork,

Which error?

**Comment by 3lvis** [comment]
@alexsanderskywork Can I have an example of your JSON file, please?

**Comment by alexsanderskywork** [comment]
@3lvis yes, you can. Please look at it https://www.dropbox.com/s/k8gzujrdc587j6t/allStations.json?dl=0

**Comment by alexsanderskywork** [comment]
@3lvis *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSDictionary initWithObjects:forKeys:]: count of objects (439) differs from count of keys (0)'

**Comment by 3lvis** [comment]
@alexsanderskywork Thanks! I'll get back to you later today :bouquet:

**Comment by alexsanderskywork** [comment]
@3lvis Thank you! I used this library in another project and I liked it

**Comment by 3lvis** [comment]
Hi Alexsander,

I think you had some errors when creating your Core Data model.

**Comment by 3lvis** [comment]
Check the full example on how I did it, here. It's working with no problems, although you might want to check the performance issues after syncing so many items.

https://github.com/hyperoslo/Sync/pull/193
