### ISSUE TITLE
use valueForKeyPath in sync_toOneRelationship

### ISSUE THREAD

**Issue by ali59a** [hyperoslo/Sync#197]
Hello, 

Is it a good approach to a good approach to use valueForKeyPath in sync_toOneRelationship so we put this line :  

` guard let managedObjectContext = managedObjectContext, filteredObjectDictionary = (dictionary as NSDictionary).valueForKeyPath(relationshipName) as? [String : AnyObject], destinationEntity = relationship.destinationEntity, entityName = destinationEntity.name, entity = NSEntityDescription.entityForName(entityName, inManagedObjectContext: managedObjectContext) else { return }`

Instead of this line : 
`guard let managedObjectContext = managedObjectContext, filteredObjectDictionary = dictionary[relationshipName] as? [String : AnyObject], destinationEntity = relationship.destinationEntity, entityName = destinationEntity.name, entity = NSEntityDescription.entityForName(entityName, inManagedObjectContext: managedObjectContext) else { return }`

I only replaced `dictionary[relationshipName]` with (dictionary as `NSDictionary).valueForKeyPath(relationshipName)` 

Thank you in advance for your answer

**Comment by 3lvis** [comment]
Hi @ali59a,

It has the same effect but `dictionary[relationshipName]` seems a more readable approach than `(dictionary as NSDictionary).valueForKeyPath(relationshipName)`.

Any special reason on why you would prefer this?

Best,
