### ISSUE TITLE
"Duplicated" entries from JSON when calling Sync

### ISSUE THREAD

**Issue by pschneider** [hyperoslo/Sync#200]
Hi,

first of all: Thanks for this great library. It really helped us a lot so far!
However today we faced a problem which wasn't present when we implemented the Sync mechanism a few weeks ago. Unfortunately I could not figure out why the following stuff happens at all, because it looks like a really strange behavior.

- We have a Core Data Entity with an property `id` which has the following settings:
 - `hyper.isPrimaryKey = YES`
 - `hyper.remoteKey = idServer` (which is the key in our JSON)

Our Sync call is pretty standard:
```swift
Sync.changes(json, inEntityNamed: entity, predicate: predicate, dataStack: LocalStorage.dataStack) { error in
....
```
The completion handler does not change anything so I cut it off.

Now we faced the following problem:

Our JSON contains 499 entries. Once the Sync is done the underlying `sqlite` Store holds 998 items and it looks like it is just 2 times the JSON. What's strange about this: The `ZID` field (id property of our entity) of the duplicates is always `0` instead of the value from `idServer`. Commenting the Sync call causes no Entries at all so I assume the "Bug" happens somewhere inside Sync or the DataStack. I could track it down to the following lines. Unfortunately I didn't had the time to dive deeper into the library just yet.
The following code is located in `DATAStack.swift` starting at line 232.

```
public func persistWithCompletion(completion: (() -> ())?) {
        let writerContextBlock: @convention(block) () -> Void = {
            do {
//                try self.writerContext.save()
                if TestCheck.isTesting {
                    completion?()
                } else {
                    dispatch_async(dispatch_get_main_queue(), {
                        completion?()
                    })
                }
            } catch let parentError as NSError {
                fatalError("Unresolved error saving parent managed object context \(parentError)");
            }
        }
        let writerContextBlockObject : AnyObject = unsafeBitCast(writerContextBlock, AnyObject.self)

        let mainContextBlock: @convention(block) () -> Void = {
            do {
                try self.mainContext.save()
                self.writerContext.performSelector(DATAStack.performSelectorForBackgroundContext(), withObject: writerContextBlockObject)
            } catch let error as NSError {
                fatalError("Unresolved error saving managed object context \(error)")
            }
        }
        let mainContextBlockObject : AnyObject = unsafeBitCast(mainContextBlock, AnyObject.self)
        self.mainContext.performSelector(DATAStack.performSelectorForBackgroundContext(), withObject: mainContextBlockObject)

    }
```
As you can see I commented out the line `try self.writerContext.save()`. Without this the `sqlite` Store  seems OK with just 499 correctly mapped Entries. Our Entity has one `to-many` relationship which gets inserted correctly and as far as I can tell is there just once for the 499 correct entries. So only the main entries are "duplicated" (with `zid = 0`) for whatever reason.

This happend with version 1.5.2 and still with 1.6.1 (updated dependencies too of course)

Do you know what could cause this problem? Could this be a problem in our code or maybe the library itself?

Any help is very much appreciated! Thank you.

**Comment by 3lvis** [comment]
Hi Patrick,

I'm sorry you're having troubles with the latests versions of Sync. What you're reporting seems like it's something in our side, but is going to be hard to tell without being able to reproduce the bug.

Would you mind sharing with me a example of your JSON structure and your Core Data model? I would love to isolate the issue in order to find a fix.

Thanks!

**Comment by pschneider** [comment]
Thanks for your fast response! Unfortunately I can't show you the real source code from our App. but I will try to reproduce the behaviour in an example Project by today or tomorrow.

**Comment by 3lvis** [comment]
@pschneider Just being able to see the kind of relationships in both the Core Data model and the JSON would help, I don't need to see which attributes you're using.

**Comment by 3lvis** [comment]
Closing for lack of more information. Please let me know if you want me to reopen this.
