### ISSUE TITLE
Not able to compile because of DATAStack ?

### ISSUE THREAD

**Issue by tanmaybaranwal** [hyperoslo/Sync#222]
I am getting errors at : 
 `NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(DATAStack.mainContextDidSave(_:)), name: NSManagedObjectContextDidSaveNotification, object: context)`
![screen shot 2016-05-20 at 7 08 26 pm](https://cloud.githubusercontent.com/assets/7475655/15429403/7465e940-1ebe-11e6-8104-2f0874eaacca.png)

**Comment by 3lvis** [comment]
Hi @tanmaybaranwal!

Which version or Swift are you using? Could be something related to the new #selector syntax on Swift 2.2.

**Comment by 3lvis** [comment]
Just gave it a fresh clone + install. I'm 99% sure, this will get fixed if you update your Xcode.

Let me know otherwise and I'll reopen the issue.
