### ISSUE TITLE
Many to Many - Relationship data not being deleted

### ISSUE THREAD

**Issue by xTheRamon** [hyperoslo/Sync#225]
Hey @3lvis! 

I think there's an issue with removing related data in a many to many relationship. I might be doing something wrong though.

Please imagine the following structure:
![structure](https://cloud.githubusercontent.com/assets/18720368/15743178/e4ae7b4a-28c3-11e6-9b3f-48558186eaea.png)

The `user.favouriteTags` do not get **deleted**. Only **updated** and **inserted**.
Please consider the following flow:

**1. Saving a brand new user.**
```
{
  "user_favorite_tags" = (
    {
      id = 13;
      hashtag = "#yolo";
    }
  );
  username = Name;
  id = 1;
}
```
**2. Updating the user with one NEW tag.**
```
{
  "user_favorite_tags" = (
    {
      id = 13;
      hashtag = "#yolo";
    },
    {
      id = 14;
      hashtag = "#onenewtag";
    }
  );
  username = Name;
  id = 1;
}
```
**3. Updating the user with another NEW tag, however, the old one (id=14) is removed.**
```
{
  "user_favorite_tags" = (
    {
      id = 13;
      hashtag = "#yolo";
    },
    {
      id = 15;
      hashtag = "#replacedtag";
    }
  );
  username = Name;
  id = 1;
}
```

You would expect the user to simply have the tags 13 and 15. However, the user has 13, 14 and 15.
This problem also occurs when:
**1. Saving a brand new user.**
**2. Updating the user with one NEW tag.**
**3. Saving the exact same data as step one.**
In this case, you'd expect the user to have the tag 13 only. The user has 13 and 14.

Thank you in advance! 👍🏼

**Comment by 3lvis** [comment]
@xTheRamon Hi! Thanks for reporting this issue, I'll try to reproduce it in a unit test. 

💐

**Comment by xTheRamon** [comment]
Hi @3lvis, did you manage to reproduce the issue or do you need some more debug information? 👍🏼

**Comment by 3lvis** [comment]
@xTheRamon Reproduced, I'm sorry this is taking so long. Crazy mix between deadlines and WWDC.

**Comment by bonebox** [comment]
Hey @3lvis!  Just checking to see if you had an update on this. I'm experiencing the same issue.

**Comment by 3lvis** [comment]
Hi! Working on a fix for this.

I'm using this model:

<img width="360" alt="screen shot 2016-08-26 at 12 23 08" src="https://cloud.githubusercontent.com/assets/1088217/18002405/e1c1a9f0-6b87-11e6-942a-5215c7ab8e40.png">

Then I'm working on 3 cases:

## Case 1: Replacing a tag with another tag

First tag with ID 10 gets inserted:

```json
[
  {
    "id": 1,
    "tags": [
      {
        "id": 10
      }
    ]
  }
]
```

Then tag 10 gets removed and tag 20 gets assigned to user instead:

```json
[
  {
    "id": 1,
    "tags": [
      {
        "id": 20
      }
    ]
  }
]
```

**Comment by 3lvis** [comment]
Please let me know if any of this doesn't make sense. I'm still yet to refactor and do some clean up but the main feature should be available shortly.

**Comment by xTheRamon** [comment]
You sir, are an absolute hero. I have just tested this (Your commit from a few seconds ago) and can confirm this is working again!

So many thanks @3lvis !!!!!! ❤️

**Comment by 3lvis** [comment]
# Released => https://github.com/hyperoslo/Sync/releases/tag/1.13.1

I'm sorry this took so long. Let me know if there are issues with this fix.

**Comment by bonebox** [comment]
Thanks, @3lvis!  When you get a chance, would you mind pushing this version to CocoaPods?  Thanks again!

**Comment by 3lvis** [comment]
Hi! It's already on CocoaPods https://github.com/CocoaPods/Specs/commit/20264d703e2c9691856e57e7b5ab1d77c31134d1

**Comment by bonebox** [comment]
Sorry! Needed to refresh my local repo.
