### ISSUE TITLE
Time conversion confusion

### ISSUE THREAD

**Issue by justinackermann** [hyperoslo/Sync#226]
Maybe I am misunderstanding how the time conversion works with Sync but take the date "2016-07-16T01:32:00-04:00" in my JSON. When importing this date into Core Data as a NSDate it is creating a timestamp of 490339920 which correlates to 1985-07-16T01:32:00-04:00. 

Could I be doing something wrong or is this a bug or am I just misunderstanding the documentation??

Thanks!

**Comment by 3lvis** [comment]
Hi @justinackermann,

I just verified this and the date parsing is correct. How did you generated the timestamp?

```swift
let resultDate = NSDate.hyp_dateFromDateString("2016-07-16T01:32:00-04:00")
// parsed date => 2016-07-16 05:32:00 +0000
// unix timestamp (timeIntervalSince1970) 1468647120.0
```
<img width="591" alt="screen shot 2016-06-03 at 07 31 44" src="https://cloud.githubusercontent.com/assets/1088217/15769634/3c967f62-295d-11e6-8d24-3d9a65b5273a.png">
