### ISSUE TITLE
Add support for custom mapping in relationships

### ISSUE THREAD

**Issue by kostiakoval** [hyperoslo/Sync#23]
Is seams like it crashing now

**Comment by NSElvis** [comment]
It's not :) Only possible for attributes

**Comment by kostiakoval** [comment]
failed: caught "NSInvalidArgumentException", "-[NSRelationshipDescription attributeValueClassName]: unrecognized selector sent to instance 0x7bf662c0"

![screen shot 2015-03-19 at 15 35 10](https://cloud.githubusercontent.com/assets/1086260/6732664/9481f1a0-ce4d-11e4-8dc6-c9e59e124dc8.png)

**Comment by NSElvis** [comment]
At the moment we are only supporting custom mapping for attributes.

The idea is to support relationships too =>https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/releases/tag/2.9

**Comment by NSElvis** [comment]
Linked to => https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/issues/52

**Comment by 3lvis** [comment]
Fixed by @RamonGilabert on https://github.com/hyperoslo/Sync/pull/36
