### ISSUE TITLE
Allow to set operations when using specific context

### ISSUE THREAD

**Issue by dersvenhesse** [hyperoslo/Sync#230]
Hi!

I came across a problem in a current project when fetching data in the background using 
```
public class func changes(changes: [[String : AnyObject]], inEntityNamed entityName: String, predicate:  NSPredicate?, parent: NSManagedObject?, inContext context: NSManagedObjectContext, dataStack: DATAStack, completion: ((error: NSError?) -> Void)?) {
```

In that case the operations are set to `.All`. I'd really like a public method to configure the operations as well when using a specific context.

My app loads a json list of entries from `api/list/cars` containing only their titles to display them in a table. When selecting one entry, the detail view shows the title and more details are loaded in the background for the specific entry via `api/car/42`. Since the other cars aren't included in this json, at the moment they'll be removed every time when entering the detail view.

**Comment by xTheRamon** [comment]
It sounds like your problem could be solved by using a predicate. Try using that same sync call with the following NSPredicate: `remoteID == 42`. You will see that only car `42` gets updated/deleted/inserted (.All) and the other values will not be touched.

**Comment by dersvenhesse** [comment]
Yep, using a predicate should work. Thanks. 
But anyhow, shouldn't there be a method allowing to use a specific context and set operations as well?
