### ISSUE TITLE
Many-to-many related objects get deleted with []

### ISSUE THREAD

**Issue by dersvenhesse** [hyperoslo/Sync#234]
Hi there,
this might be related to #225 but I'd like to let you know anyways.

I'm using many-to-many relationships like in this [forked SyncAppNetDemo](https://github.com/dersvenhesse/SyncAppNetDemo). 

When the `global.json` is at first

```
{
    "garage": [{
        "name": "Alice",
        "id": 1,
        "cars": [{
            "id": 1,
            "name": "Alfa Romeo"
        }, {
            "id": 2,
            "name": "Aston Martin"
        }, {
            "id": 5,
            "name": "Audi"
        }]
    }, {
        "name": "Bob",
        "id": 2,
        "cars": [{
            "id": 3,
            "name": "Bugatti"
        }, {
            "id": 6,
            "name": "Bentley"
        }]
    }]
}
``` 

and then

````
{
    "garage": [{
        "name": "Alice",
        "id": 1,
        "cars": [{
            "id": 1,
            "name": "Alfa Romeo"
        }, {
            "id": 2,
            "name": "Aston Martin"
        }, {
            "id": 5,
            "name": "Audi"
        }]
    }, {
        "name": "Bob",
        "id": 2,
        "cars": []
    }]
}
````

the cars from the first person will be deleted as well. 

Since ` "cars": []` is valid JSON, this shoudn't delete all cars. Or am I missing something?

**Comment by 3lvis** [comment]
Thanks @dersvenhesse, you're correct this is related to #225 this is on the top of my list.

**Comment by dersvenhesse** [comment]
I just checked this again with 1.13.1. Now it works for me. 👍

**Comment by 3lvis** [comment]
That's great news! Thanks for reporting back, @dersvenhesse. You're awesome.

![giphy](https://cloud.githubusercontent.com/assets/1088217/18032828/6c06514c-6d13-11e6-8790-baf067f50549.gif)
