### ISSUE TITLE
Search for relationships in superentities

### ISSUE THREAD

**Issue by Jonge** [hyperoslo/Sync#238]
Hi,

When a parent object is defined, Sync doesn't search for relationships in superentities.

Imagine you have an object `Car` with a relationship `ownedBy` pointing to another object `Person`. Create an object `Racecar` having `Car` as a superentity. Now, when you perform a sync with an explicitly defined `Person` as a parent, it fails.

See pull request https://github.com/hyperoslo/Sync/pull/239 with an example how to fix this.

**Comment by 3lvis** [comment]
Thanks a lot for this. I'm very sorry it took this long to merge. I moved your test case here to fix the conflicts and simplified a bit the test case.

Have a fantastic week!

https://github.com/hyperoslo/Sync/pull/264
