### ISSUE TITLE
Unit testing and fetching Core Data objects

### ISSUE THREAD

**Issue by tbechtum** [hyperoslo/Sync#244]
Hello !

When calling Sync.changes and mapping the executeFetchRequest result like e.g.
try dataStack.mainContext.executeFetchRequest(requestRequest) as! [OwnManagedObject]
then this works only when running as application (e.g. Xcode iOS simulator) but not when running as a XCTestCase test unit accessing the result (by count or for loop iteration),  which fails with
fatal error: NSArray element failed to match the Swift Array Element type. How I have to implement the CoreData managed object that Xcode unit testing is working too?

Using currently this pattern
@objc(OwnManagedObject) // Needed for Sync usage
public class OwnManagedObject: NSManagedObject {}

Thanks for your help,
cheers
Thomas

**Comment by 3lvis** [comment]
Hi @tbechtum,

That's a weird bug, I can only think of it as a Swift bug, nothing related to Sync. I'm sorry I can't be more helpful. Maybe you need to add `CoreData` to your Test bundle?

**Comment by tbechtum** [comment]
Thanks for your quick reply 3lvis!
Yes importing CoreData and the test unit is compiling, the exception is at runtime in the test environment.

**Comment by 3lvis** [comment]
It works, I tried in a throw away branch. https://github.com/hyperoslo/Sync/blob/9fb41745daee0b7a843967e776aecc8c1aa4994b/Tests/SyncTests.swift#L647-L649
