### ISSUE TITLE
Relationships are nil when using CamelCase relationship names

### ISSUE THREAD

**Issue by RobinFalko** [hyperoslo/Sync#252]
Setting up the "User  <->> Notes" example and changing the User relationship name from "notes" to "myNotes" (or other CamelCase names) will result in an ignored relationship object. Only the User object will be inserted into the DB.

A workaround was to add the user info `hyper.remoteKey = myNotes` on the User.myNotes relationship.

**Comment by 3lvis** [comment]
@RobinFalko Thanks! I'll look into it. Makes sense that this is a bug at the moment since the camelCase support was added to https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper first and we didn't made the change in Sync.

Thanks for reporting this issue!

Best,

**Comment by RobinFalko** [comment]
Thanks for looking into into it and keep up the great work. I really like your framework.

**Comment by 3lvis** [comment]
Should be fixed here https://github.com/hyperoslo/Sync/pull/258
