### ISSUE TITLE
HyperDate Report Error on Device but works fine on simulator

### ISSUE THREAD

**Issue by smartjx** [hyperoslo/Sync#253]
When I run the sync, it works great on simulator. But when I run the sync on my device. It crashed with hyperdate error. 

NSDate+HYPPropertyMapper.m-> +hyp_dateFromISO8601String

 signal SIGABRT

Please help, thank you:)

**Comment by 3lvis** [comment]
Hi @smartjx!

Can I get an example of your JSON file? Or just your JSON date object?

**Comment by smartjx** [comment]
Hi 3lvis,

Thank you so much for your reply. 
Please find my json data object below. Thank you for taking time for investigate this issue again.

[{"Project_ID":1,"Name":"工程加固\r\n","Type":null,"Project_FB_ID":1,"Scale":"≤20m\r\n","OrderNo":100,"UpdateTime":"2016-01-09T21:29:29.41","Status":0},{"Project_ID":2,"Name":"工程降水\r\n","Type":null,"Project_FB_ID":1,"Scale":"≤20m\r\n","OrderNo":100,"UpdateTime":"2016-01-09T21:29:29.41","Status":0}]

**Comment by smartjx** [comment]
I can't find anything wrong during the date parsing.  I add the following line to parse the 2016-01-09T21:29:29.41 in order to prevent it from falls to else condition but still crash.

NSDate+HYPPropertyMapper.m 
+ (NSDate *)hyp_dateFromISO8601String:(NSString *)dateString  
{
else if (originalLength == 23 && originalString[19] == '.') {
            strncpy(currentString, originalString, 19);
            //hasTimezone = YES;
            hasMiliseconds = YES;
        }

else {
            strncpy(currentString, originalString, originalLength > 24 ? 24 : originalLength);
        }

}

**Comment by smartjx** [comment]
Hi 3lvis,

Sorry for waste your time investigate this issue. This is non-issue. It's the MBPROGRESSHUD that I used to load the sync stopped the process that right after date parsing.

I closed this issue and thank you again for your time.

**Comment by 3lvis** [comment]
Yay!!! Let me know if there's anything else I can help with :) Have a fantastic day

**Comment by smartjx** [comment]
Hi 3lvis,

I have to re-open this issue. And I found it's not MBProgressHUD issues. 

My current implementation is that I download a big json file that include multiple entities. Then I use multiple (5+) Sync.changes to save these entites to each entity. My app always crash at the second Sync.changes.  

 let PAdataToSave = data["ResultSet"]!["ProjectInfo"] as! [[String : AnyObject]]
                Sync.changes(PAdataToSave, inEntityNamed: "ProjectInfo", dataStack:   dataStack, completion: { error in
                    print("Sync Error = ",error)
                })
                
                let PConsdataToSave = data["ResultSet"]!["ProjectConsLogInfo"] as! [[String : AnyObject]]
                Sync.changes(PConsdataToSave, inEntityNamed: "Cons_Log", dataStack:   dataStack, completion: { error in
                    print("Sync Error = ",error)
                })

**Comment by 3lvis** [comment]
I'll have a second look :)

**Comment by smartjx** [comment]
Hi 3lvis，

Thank you for your time. For better investigate this issue. I have modified your demo app, add my core data structure and my api link. Please find the modifed app below. You can immediately reproduce this issue. When you run the demo on device. And you can see it works great on simulator without any error.
[
[SyncAppNetDemo-master.zip](https://github.com/hyperoslo/Sync/files/412619/SyncAppNetDemo-master.zip)
](url)

**Comment by smartjx** [comment]
I've locate the crash due to  hyp_dateFromDateString date parsing
I comment it out and it works fine now. But the issue still hasn't resolved.
```

  //  value = [NSDate hyp_dateFromDateString:remoteValue];
        
        NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
        formatter.dateFormat = @"yyyy-MM-dd HH:mm:ss";
        
        value = [formatter dateFromString:remoteValue];

```

**Comment by smartjx** [comment]
Hi 3lvis,

I found the reason. Any unkonwn date format will crash 

```
NSDate+HYPPropertyMapper.m-> +hyp_dateFromISO8601String
at line 164 
struct tm tm;
        if (strptime(currentString, "%FT%T%z", &tm) == NULL) {
            return nil;
        }
```
I add my date format here and it works now. 
 ```
      // Copy all the date excluding the miliseconds.
        // Current date: 2014-03-30T09:13:00.000
        // Will become:  2014-03-30T09:13:00
        // Unit test G
        else if (originalLength == 23 && originalString[19] == '.') {
            strncpy(currentString, originalString, 19);
            hasMiliseconds = YES;
        }


```

**Comment by 3lvis** [comment]
I'm glad you found the source. That sounds 100% correct. I'm handling dates like this because is MUCH MUCH MUCH more performant than using NSDateFormatter.

**Comment by smartjx** [comment]
But still, I don't get why this works on simulator without any crash.

**Comment by 3lvis** [comment]
Yeah, that's *very* strange.

**Comment by smartjx** [comment]
Hi 3lvis,

 Thank you for your confirmation. I've modified my local copy of NSDate+HYPPropertyMapper.m and   commited to your repo:NSManagedObject-HYPPropertyMapper/Source/NSDate+HYPPropertyMapper.m.
If you are ok with the change , please kindly merge it, thank you.

**Comment by 3lvis** [comment]
@smartjx does this fixes your problem?

https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/pull/110

**Comment by 3lvis** [comment]
Fixed here https://github.com/hyperoslo/Sync/releases/tag/1.11.2
