### ISSUE TITLE
DateParser doesn't work correctly, when unixTimestamp has negative value

### ISSUE THREAD

**Issue by AnteyA** [hyperoslo/Sync#270]
For example, if i have unixTimestamp='-2209150800000' (1899-12-30T03:00:00Z), in DB it will be NULL

Error in this code: 
@implementation NSString (HYPPropertyMapperDateHandling)
- (HYPDateType)hyp_dateType {
    if ([self containsString:@"-"]') {
        return HYPDateTypeISO8601;
    } else {
        return HYPDateTypeUnixTimestamp;
    }
}
@end

Function should return a value HYPDateTypeUnixTimestamp instead of HYPDateTypeISO8601

**Comment by 3lvis** [comment]
Thanks! Feel free to send a fix :)

Otherwise I'll have a look on the weekend, I've been pretty busy lately.

**Comment by 3lvis** [comment]
Fix for: https://github.com/hyperoslo/Sync/issues/270

This is the simplest way that I've found to support this feature, using regular expressions instead of simple string comparison has it's drawbacks, the method calculation went from 0.01 to 0.02. Since date parsing is a common thing that could be done thousands of times in a JSON mapping, I would prefer to keep the performance instead of handling this edge case, as I've found online most current unix timestamp parsers don't even support this feature.

Please let me know what you think.

**Comment by AnteyA** [comment]
I forgot to answer.
I had to change function hyp_dateType: so it solve my problem
- (HYPDateType)hyp_dateType {
    if ([self containsString:@"-"] && [self length] > 0 && ![[self substringToIndex:1] containsString:@"-"]) {
        return HYPDateTypeISO8601;
    } else {
        return HYPDateTypeUnixTimestamp;
    }
}

Also i had to change function hyp_dateFromUnixTimestampString, because in this function is using fixed timestamp length (but timeStamp length may be from 0 to 14/more):
+ (NSDate *)hyp_dateFromUnixTimestampString:(NSString *)unixTimestamp {
    NSString *parsedString = unixTimestamp;

    /*
    NSString *validUnixTimestamp = @"1441843200";
    NSInteger validLength = [validUnixTimestamp length];
    if ([unixTimestamp length] > validLength) {
        if ([unixTimestamp length] == 14) {
            parsedString = [unixTimestamp substringToIndex:(validLength + 1)];
        } else {
            parsedString = [unixTimestamp substringToIndex:validLength];
        }
    }
    */
    if ([parsedString length] > 3) {
        parsedString = [parsedString substringToIndex:[parsedString length] - 3];
    }

    NSNumberFormatter *numberFormatter = [NSNumberFormatter new];
    numberFormatter.numberStyle = NSNumberFormatterDecimalStyle;
    NSNumber *unixTimestampNumber = [numberFormatter numberFromString:parsedString];
    NSDate *date = [[NSDate alloc] initWithTimeIntervalSince1970:unixTimestampNumber.doubleValue];

    return date;
}

in any case, thanks for the answer, and especially for your library.
your library is very cool and has helped me in my project.

**Comment by 3lvis** [comment]
That's very nice of you, I wish you an amazing week 🌞
