### ISSUE TITLE
Inconsistent JSON to CoreData mapping

### ISSUE THREAD

**Issue by Proper-Job** [hyperoslo/Sync#273]
First of all thank you for sync.  It's great!

I'm experiencing some inconsistencies in how JSON keys are mapped to CoreData attributes.
For instance the JSON key "list_image_url" does not automatically map to the CoreData attribute "listImageUrl".  Only when I add hyper.remoteKey = list_image_url does the mapping take place.

This behavior is a bit erratic in my experience.  For instances JSON "last_modified" maps just fine to "lastModified".

As a safeguard I started adding hyper.remoteKey to all attributes.

**Comment by 3lvis** [comment]
Hi! That's because `list_image_url` maps to `listImageURL`!

**Comment by 3lvis** [comment]
It works like that because URL is an acronym. You can find the complete list of acronyms here.

https://github.com/hyperoslo/NSString-HYPNetworking#acronyms

**Comment by Proper-Job** [comment]
@3lvis thank you for that!

**Comment by 3lvis** [comment]
Updated the README to clarify this, sorry for not adding that before :)

https://github.com/hyperoslo/Sync/blob/master/README.md#attribute-mapping
