### ISSUE TITLE
Add support for flattening out deep JSON structures with keyPaths

### ISSUE THREAD

**Issue by marthinfreij** [hyperoslo/Sync#274]
Some REST APIs have data in deep structures where relations makes no sense. In these cases it would be nice to be able flatten out the JSON structure in the model object by picking values in deep structures using keyPaths.

## Example

Given this JSON structure:

```javascript
{
  "title": {
    "rendered": "Hello, World!"
  }
}
```

Making a relationship from `title` to `rendered` wouldn't make sense. By letting `hyper.remoteKey` support keyPaths, we could easily map the `title` attribute in our model to a `title.rendered` keyPath.

This feature should support unlimited depths. The bool in the following structure would be mappable to `hyper.remoteKey = some.very.deep.structure`.

```javascript
{
  "some": {
    "very": {
      "deep": {
        "structure": true
      }
    }
  }
}
```

It should also support when a structure have multiple values on the same level. The strings in the example below should be mappable to `hyper.remoteKey = content.rendered` and `hyper.remoteKey = content.edit`.

```javascript
{
  "content": {
    "rendered": "<p>Hello, World!</p>",
    "edit": "Hello, World!"
  }
}
```

**Comment by 3lvis** [comment]
Fantastic idea! I remember wanting to do something like this before, I'm glad you're bringing it again.

**Comment by 3lvis** [comment]
# BOOM! Added in 2.1.0

**https://github.com/hyperoslo/Sync/releases/tag/2.1.0**

And [Sync 1.14.0](https://github.com/hyperoslo/Sync/releases/tag/1.14.0) if you're still in Swift 2.3
