### ISSUE TITLE
Add support for value transformations for built in Core Data types

### ISSUE THREAD

**Issue by marthinfreij** [hyperoslo/Sync#275]
Sometimes values in a REST API are not formatted in the way you want them, resulting in you having to extend your model classes with methods and/or properties for transformed values.

## Example

Some APIs return HTML encoded entities in string values.

```javascript
{
  "title": "Foo &#038; bar"
}
```

This requires your client to handle HTML entitles each time you need `title`.

## Feature request

Wouldn't it be nice if it was possible to hook into Sync and transform during the property mapping process? Sync supports transformable attributes in Core Data, but the problem is that Core Data will persist them as NSData. Having a simple string such as title stored as NSData is not optimal. It would be much better is one could specify a NSValueTransformer for attributes of the built in Core Data types.

**Comment by 3lvis** [comment]
# BOOM! Added in 2.1.0

**https://github.com/hyperoslo/Sync/releases/tag/2.1.0**

And [Sync 1.14.0](https://github.com/hyperoslo/Sync/releases/tag/1.14.0) if you're still in Swift 2.3
