### ISSUE TITLE
Swift3 Support?

### ISSUE THREAD

**Issue by jimijon** [hyperoslo/Sync#276]
Finally decided to go with XCode8 / Swift3. Change my pod file to get the swift-3 branch, but, still have lots of compile time errors.

Comments?

**Comment by 3lvis** [comment]
Hi! I'm having a hard time migrating because lots of issues regarding pushing new builds with CocoaPods. I'm working on it :)

**Comment by jimijon** [comment]
Do you have an approximate ETA? I have to finish up for an upcoming Demo. So if it is in the next couple days I can wait, otherwise I need to rollback.  Thanks! Or. if there is something very specific that you can point me to. I might be able to help fix things.

**Comment by 3lvis** [comment]
Hi! It's coming later today. Already migrated some of the dependencies, just need to finish some migration on this repo.

**Comment by 3lvis** [comment]
The main blocker so far was CocoaPods, but they have been very helpful to fix things. Did you knew that now you have to add a `.swift-version` file to your repo in order to ship a pod with Swift 3? No? Me neither. Mindblown.

**Comment by 3lvis** [comment]
Branch in progress here https://github.com/hyperoslo/Sync/pull/279

**Comment by 3lvis** [comment]
It's on master now, for now just point directly to `:head`

**Comment by 3lvis** [comment]
```
pod 'Sync', git: 'git@github.com:hyperoslo/Sync.git'
```

**Comment by jimijon** [comment]
did you lock down the repo? Or cocoa pod problem? This is what I get ::

[!] Error installing Sync
[!] /usr/bin/git clone git@github.com:hyperoslo/Sync.git /var/folders/08/3tkjvm5n33dgcs3b285qjgmm0000gn/T/d20160914-97058-muxjqr --template= --single-branch --depth 1

Cloning into '/var/folders/08/3tkjvm5n33dgcs3b285qjgmm0000gn/T/d20160914-97058-muxjqr'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by 3lvis** [comment]
Seems like a CocoaPods problem

**Comment by 3lvis** [comment]
Released as Sync 2.0.0

https://github.com/hyperoslo/Sync/releases/tag/2.0.0
