### ISSUE TITLE
Uncaught exception when syncing a to-many relationship

### ISSUE THREAD

**Issue by pwestrich** [hyperoslo/Sync#280]
Since attempting to update to the latest version of Sync (2.0.0) and Xcode (8.0), from 1.12.3 and 7.3 respectively. I have been experiencing a crash due to an [uncaught exception](https://github.com/hyperoslo/Sync/files/473187/trace.txt).

It happens at NSManagedObject_Sync.swift:185. It appears that one of my managed objects (ICRoutePolylineItem) is being asked for the key "busID", which it has never had, let alone has it been a primary key. Here's my managed object model and an [example](https://github.com/hyperoslo/Sync/files/473204/example.txt) of the JSON being synced:
 ![model](https://cloud.githubusercontent.com/assets/7771375/18524488/2f34771c-7a7e-11e6-9baf-b0e4d377bc71.png)

Normally, the JSON would have more specific addresses and coordinates, but I removed them for the purpose of example. I have ensured that the managed object model properly maps remote primary keys to their appropriate local ones, as I had to match the mapping given to me form the remote server. I haven't modified those mappings for a while, and it did not manifest itself until updating to version 2.0.0, so I don't believe that is the issue.

I feel that Sync is confused as to which entity it is wanting the primary key from, because the other end of the relationship has the primary key it's looking for, but not this one.

**Comment by 3lvis** [comment]
Thanks a lot for reporting this issue, sadly at the moment I'm really busy at work. Hopefully I'll get time to have a look at this issue early next week, I hope that's ok for you. Have a good weekend!

But as always PRs are very welcome, if there's something hard to understand I can take some time to give some guidance.

**Comment by 3lvis** [comment]
@pwestrich Could you help me by saying what are you using for primary key in each entity?

**Comment by 3lvis** [comment]
Working on a fix here, but need more info to reproduce: https://github.com/hyperoslo/Sync/pull/290

**Comment by pwestrich** [comment]
busId is the primary key for both Bus and Route, and index is the primary key for RouteStop and RoutePolylineItem.

**Comment by 3lvis** [comment]
@pwestrich Thanks!

**Comment by 3lvis** [comment]
Hi again @pwestrich 

I haven't been able to reproduce the issue. Do you have any idea what I might be missing?

https://github.com/hyperoslo/Sync/pull/290

**Comment by pwestrich** [comment]
I'm not sure. From what I can see your managed object model and JSON look like mine. I'm nowhere near my work computer at the moment. I'll see what I can do Monday morning when I'm back.

**Comment by 3lvis** [comment]
@pwestrich Don't worry! Have a great weekend 🎉

**Comment by 3lvis** [comment]
@pwestrich I was able to reproduce the bug by calling Sync two times, one after the other. Seems like the crash is related to updating.

**Comment by pwestrich** [comment]
I do have two calls to Sync, but removing the second one has no effect; it's the first one that causes it, which is the one that updates the Route and its subset of objects.
I have confirmed that your model and JSON do look like mine.

**Comment by 3lvis** [comment]
Issue fixed here: https://github.com/hyperoslo/Sync/pull/290 🎉 

Should be available through CocoaPods in the upcoming Sync release.

**Comment by 3lvis** [comment]
# [Fixed on Sync 2.1.2](https://github.com/hyperoslo/Sync/releases/tag/2.1.2)

**Comment by pwestrich** [comment]
Awesome. Thanks a lot.
