### ISSUE TITLE
Duplicate entries when sync to core data

### ISSUE THREAD

**Issue by ro22e0** [hyperoslo/Sync#281]
It creates two objects when passing an array of 2 same json.

**Comment by Proper-Job** [comment]
@ro22e0 You might need to set the predicate in your Sync.changes call.

**Comment by 3lvis** [comment]
@ro22e0 Would you mind proving an example of your Core Data model and the JSON that you're using? 

Should be easy to figure out what's missing with some more info.

**Comment by ro22e0** [comment]
my model
<img width="134" alt="capture d ecran 2016-09-16 a 14 17 17" src="https://cloud.githubusercontent.com/assets/11290982/18585649/7287599e-7c18-11e6-87c9-ac8d73b11b94.png">

and the json

`[
  {
    "events" : [
    ],
    "owners" : [
      {
        "status" : "owner",
        "school" : null,
        "promotion" : null,
        "id" : 3,
        "company" : null,
        "image" : null,
        "email" : "thomas@mail.com",
        "mutual_friends" : [
        ],
        "group" : null,
        "job" : null,
        "name" : null
      }
    ],
    "participating_users" : [
    ],
    "id" : 3,
    "refused_users" : [
    ],
    "invited_users" : [
    ],
    "name" : "default"
  },
  {
    "events" : [
    ],
    "owners" : [
      {
        "status" : "owner",
        "school" : null,
        "promotion" : null,
        "id" : 3,
        "company" : null,
        "image" : null,
        "email" : "thomas@mail.com",
        "mutual_friends" : [
        ],
        "group" : null,
        "job" : null,
        "name" : null
      }
    ],
    "participating_users" : [
    ],
    "id" : 3,
    "refused_users" : [
    ],
    "invited_users" : [
    ],
    "name" : "default"
  }
]`

**Comment by dersvenhesse** [comment]
Since your JSON contains two entries respectively two model instances Sync is totally right to create two objects as well.

**Comment by pwestrich** [comment]
However, if id is the primary key for the Owner object, we shouldn't allow two objects with the same primary key, as they should be unique.

**Comment by 3lvis** [comment]
Closing this one for lack of more information from the original author. Let's revisit this later when we know more.
