### ISSUE TITLE
Type 'Date' has no member 'classForCoder'

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [hyperoslo/Sync#282]
Can you please let me know how to fix this?

`~/Pods/Sync/Source/NSArray+Sync.swift:16:29: Type 'Date' has no member 'classForCoder'`

`let validClasses = [Date.classForCoder(), NSNumber.classForCoder(), NSString.classForCoder()]`

Sync - 2.0.0
Xcode 8 GM
Swift 3.0
OS X 10.11.6

**Comment by 3lvis** [comment]
Hi @AnnieNinaJoyceV!

This should be different on Sync 2.0.0 => https://github.com/hyperoslo/Sync/blob/2.0.0/Source/NSArray%2BSync.swift#L16

Try deleting your Pods folder, cleaning your CocoaPods cache folder and trying again.

**Cleaning your CocoaPods cache folder**:
```ruby
pod cache clean --all
```

**Comment by AnnieNinaJoyceV** [comment]
Yes, that fixed it. Thanks for the help! 👍

**Comment by 3lvis** [comment]
Awesome! Have a great weekend 🎉
