### ISSUE TITLE
One entity as separate relationships, incorrect import

### ISSUE THREAD

**Issue by Sorix** [hyperoslo/Sync#283]
I have model with 2 relationships using same entities but with different goal. For example I have `Task` entity with 2 relationships: `owner` and `participants`. Both relationships use entity `User`. When I try to import any JSON with `owner` set, Sync also fills `participants` with same data (but there is no participants set, only owner relationship).

![model](https://cloud.githubusercontent.com/assets/5610904/18619442/70fb9bfc-7e0d-11e6-9a17-51712b8fce23.png)

I used that JSON to import:

```json
{
  "id": "tasklist2",
  "owner": {
    "id": "owner",
    "name": "test owner"
  }
}
```

In result Sync fills `Tasklist` with `owner` and `participants` entity however I've defined only `owner` relationship.

I've created test XCode project to demonstrate that issue, it is attached here: [hypbug2.zip](https://github.com/hyperoslo/Sync/files/479014/hypbug2.zip)

**Comment by 3lvis** [comment]
Hi @Sorix,

Which version of Sync are you using? :)

**Comment by 3lvis** [comment]
Nevermind, found it in the included project. Thanks!

**Comment by Sorix** [comment]
That diff is solved my issue after my investigations. I can't open pull request because I'm not sure that it is complete and correct solution, it was discovered more like "random", also I don't know if it work for whole Sync (I've fixed only in `sync_fillWithDictionary` method), I haven't look at all Sync sources yet :)

But I've check at my more complex database and I don't see any bugs yet.

But that maybe helpful for you in fixing that bug.

```diff
--- a/Source/NSManagedObject+Sync.swift
+++ b/Source/NSManagedObject+Sync.swift
@@ -46,7 +46,7 @@ public extension NSManagedObject {
                 } else {
                     sync_toManyRelationship(relationship, dictionary: dictionary, parent: parent, parentRelationship: parentRelationship, dataStack: dataStack, operations: operations)
                 }
-            } else if let parent = parent , !parent.isEqual(value(forKey: relationship.name)) && relationship.destinationEntity?.name == parent.entity.name || relationship.destinationEntity?.name == parent.entity.superentity?.name {
+            } else if let parent = parent , !parent.isEqual(value(forKey: relationship.name)) && relationship.destinationEntity?.name == relationship.name || relationship.destinationEntity?.name == parent.entity.superentity?.name {
                 setValue(parent, forKey: relationship.name)
             } else if let localPrimaryKey = dictionary[keyName] , localPrimaryKey is NSString || localPrimaryKey is NSNumber || localPrimaryKey is NSNull {
                 sync_toOneRelationshipUsingIDInsteadOfDictionary(relationship, localPrimaryKey: localPrimaryKey, dataStack: dataStack)
```

**Comment by 3lvis** [comment]
Hahaha, fantastic detective work!

**Comment by 3lvis** [comment]
Fixed here https://github.com/hyperoslo/Sync/pull/291

**Comment by 3lvis** [comment]
This was a bigger issue than what it seemed, but most people probably haven't reached since it's not a common scenario to have 2 relationships point to the same entity.
