### ISSUE TITLE
hyper.isPrimary doesn't seem to work.

### ISSUE THREAD

**Issue by jimijon** [hyperoslo/Sync#294]
Ok -

In my CoreData I have remoteID along with remoteCode (string). I want remoteCode to be the primary key. I set remoteCode in Xcode to hyper.isPrimaryKey / true in User Info.

When I run my sync, no records are added into the database.

**Comment by xTheRamon** [comment]
I'm not sure, but try adding a ’hyper.remoteKey’ as well. Might be working after that!

**Comment by 3lvis** [comment]
Great suggestion, @xTheRamon. That should fix the issue @jimijon. Let us know otherwise.

**Comment by jimijon** [comment]
OK, I got it to work by adding hyper.remoteKey. However, this should be reflected in the documentation.

**Comment by 3lvis** [comment]
@jimijon it is :) 

https://github.com/hyperoslo/Sync#using-hyperisprimarykey-in-addition-to-hyperremotekey

**Comment by 3lvis** [comment]
Moved the mentioned information from FAQ to it's corresponding section.

https://github.com/hyperoslo/Sync/blob/master/README.md#primary-key

**Comment by jimijon** [comment]
Back to this. It doesn't work for me. In my core data model I do have remoteID BUT I don't want to use that. So, I first added, hyper.remoteKey = nfCode to the table, and then I added, hyper.isPrimaryKey = true on the nfCode attribute.

The JSON data is "nfCode" also. Thoughts?

**Comment by 3lvis** [comment]
You have to add both to the attribute.

**Comment by 3lvis** [comment]
Not to the table :)
