### ISSUE TITLE
Support custom primary keys

### ISSUE THREAD

**Issue by NSElvis** [hyperoslo/Sync#31]
At the moment we are using `id` for a primary key but that's not the case for all the backends.

The idea is to support something like the custom mappers =>https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/releases/tag/2.9

So adding a `@{@"sync.primary_key" : @"YES"}` would treat the selected attribute as a primary key

Linked to => https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/issues/51

**Comment by RamonGilabert** [comment]
This was fixed here: #33 :dancers:
