### ISSUE TITLE
Screencast

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Sync#49]
I was thinking on making a screencast on how to make a Designer News client under 10 minutes using **Sync**.

- Create Xcode project (`Swift` + `Core Data`)
- Add `Podfile` (`Sync` + `DATASource` + `Networking`), run `pod install`
- Hook up TableView with `DATASource`
- Call `Sync` from the `ViewController`
- PROFIT

What do you guys think?

**Comment by kostiakoval** [comment]
This would give huge buff!!  Great idea!

**Comment by RamonGilabert** [comment]
I'll do it! :P

**Comment by 3lvis** [comment]
@RamonGilabert I'm already on it :stuck_out_tongue:

**Comment by RamonGilabert** [comment]
@3lvis awesome :)

**Comment by zenangst** [comment]
:star2:

**Comment by jgorset** [comment]
I'd watch this!

**Comment by salimos** [comment]
already waiting 💖

**Comment by zenangst** [comment]
@salimos for Travis?

**Comment by 3lvis** [comment]
Oh no! Is this going to be fill with :+1: too?!

**Comment by salimos** [comment]
@zenangst  actually the Screencast :D

**Comment by 3lvis** [comment]
Now that I know this is a good idea, no need to keep an issue on it. Will update when done.
