### ISSUE TITLE
Integrate networking

### ISSUE THREAD

**Issue by RamonGilabert** [hyperoslo/Sync#51]
I was thinking today, all the classes of the networking part are pretty similar if you use Apple's networking, so I was thinking in adding a method that let you just type Sync from that URL into this entityName, so the user, in the same ViewController for example, can just type:

```objc
[Sync changesFromURL:@"Whatever"
                                       inEntityNamed:@"Story"
                                           dataStack:dataStack
                                          completion:^(NSError *error) {
                                          }];
```

Then we would do all the requests and stuff! :)

**Comment by RamonGilabert** [comment]
Right, in the JSON you need which key it's going to contain your dictionary, so I guess the method would add a line: `withKeyInJSON:` or something.

**Comment by 3lvis** [comment]
I really like how you think but sadly this spans over the scope of Sync.
>Sync eases your every day job of parsing a JSON response and getting it into Core Data. It uses a convention over configuration paradigm to facilitate your workflow.

But this seems like a wonderful idea for a project on top of what we have!
