### ISSUE TITLE
MagicalRecord integration

### ISSUE THREAD

**Issue by skywinder** [hyperoslo/Sync#56]
Hi. Did you try to combine your project with [MagicalRecord](https://github.com/magicalpanda/MagicalRecord)?

I see, that it closely integrated with `DATAStack` and it seems, like quite bit different way to manage with  Core Data, than `Magical Record` implementation.

MR use simple method:
```obj-c
    + (void)setupCoreDataStack;
```
for initialisation of DataStack)

Is there any way to integrate `Sync` with `MagicalRecord`?

**Comment by 3lvis** [comment]
Hi @skywinder, interesting thought, at the moment MagicalRecord and DATAStack clash and they couldn't live together.

Could be interesting to replace DATAStack with MagicalRecord thought.

We'll make a pros and cons list and think about it.

Personally I think MagicalRecord it's a pretty massive dependency that I would rather not have.

**Comment by 3lvis** [comment]
@skywinder Any reason why you would prefer MagicalRecord over DATAStack?

**Comment by skywinder** [comment]
According:
- [NShipster reference](http://nshipster.com/core-data-libraries-and-utilities/)
- According GithubStars
- A lot of references to it over the internet.

I tend believe that this most common "Core Data wrapper". 
And a lot of apps already use it in their apps
As a particular case: I would like to use, `Sync` in my app too, but have no idea, how to integrate it with my project, that use MagicalRecord already.
I will let you know, if I found some solution for it.

**Comment by 3lvis** [comment]
@skywinder Interesting points :point_up:

**Comment by 3lvis** [comment]
Hi Petr! At the moment we will keep only supporting `DATAStack` it's pretty lightweight and it fits our needs.

We will reconsider it if we get more requests.

`DATAStack` [provides a simple way to create a Core Data stack](https://github.com/3lvis/DATAStack/blob/master/Source/DATAStack.h#L23), if there's anything you miss from MagicalRecord let us know and we could collaborate into make it more awesome. :grin:
