### ISSUE TITLE
Custom primary keys with custom remoteKey values cause incorrect sync behavior

### ISSUE THREAD

**Issue by bmnick** [hyperoslo/Sync#58]
When an attribute of an entity has both hyper.isPrimaryKey and hyper.remoteKey defined, an incorrect value is used for fetching existing objects from the database. -[NSEntityDescription(Sync) sync_remoteKey] doesn't take the hyper.remoteKey property into account. 

For example, in my use case, I have a local property "imageId" and a remote JSON property for the primary key of "ImageId". I have "ImageId" stored under hyper.remoteKey for this property. sync_remoteKey then takes the value from sync_localKey, which is the correct "ImageId" string and pushes it through hyp_remoteString which changes it to "image_id", which isn't present in the JSON. As a result, no remote IDs are located, no local objects can be fetched, and updates and deletions never happen.

**Comment by 3lvis** [comment]
Hi Ben!

Thanks for reporting this issue, I'll see if I can reproduce it.

Is there any reason why you would need to use `imageId` instead of the default `remoteID`?

**Comment by bmnick** [comment]
Nope, no particular reason for the naming on the local side, that's just what was used when I wrote the original data layer.

**Comment by 3lvis** [comment]
Fair enough :grin:

**Comment by bmnick** [comment]
I've got a partially complete fix locally, let me polish it up a bit and I can send over a PR.

**Comment by 3lvis** [comment]
@bmnick fantastic! Would be great to hear what do you think about us uppercasing acronyms? Looks like you use `imageId` while we use `imageID`.

https://github.com/hyperoslo/NSString-HYPNetworking#acronyms

**Comment by bmnick** [comment]
I'm not opposed to either case style. Convention here at work is for objectId, but I believe that objectID is more conventional in Cocoa/Cocoa Touch overall. Downsides of working at a primarily non-iOS shop... :confused:

**Comment by 3lvis** [comment]
@bmnick Does your JSON looks like this?

```json

[
  {
    "ImageId": 0,
    "url": "http://sample.com/sample0.png"
  },
  {
    "ImageId": 1,
    "url": "http://sample.com/sample1.png"
  },
  {
    "ImageId": 2,
    "url": "http://sample.com/sample2.png"
  }
]
```
