### ISSUE TITLE
Attribute to skip syncing

### ISSUE THREAD

**Issue by risp** [hyperoslo/Sync#62]
Would it be possible to add an attribute to an entity and based on the value the changes are not synced? 

This is very useful in an app where you want to support offline usage. For example: If the user is makes changes to an object but the app has no internet connection, his changes are saved in core data. Now when he does a pull to refresh his changes will be overwritten. If there would be such an attribute the syncing for this object would be skipped.

Similar to this a modified attribute would be useful, if the modified attribute doesn't differ from the value in the JSON syncing should be skipped improving performance.

**Comment by 3lvis** [comment]
Hi Bart!

We'll add this to the README, but today you can achieve what you just mentioned by supplying a `NSPredicate`.

So for example you could say "Sync Users excluding offline ones".

```objc
NSPredicate *predicate = [NSPredicate predicateWithFormat:@"isOffline = %@", @NO];
[Sync changes:JSON
inEntityNamed:@"User"
    predicate:predicate
    dataStack:dataStack
   completion:^{
       // New objects have been inserted
       // Existing objects have been updated
       // And not found objects have been deleted
    }];
```

Here your Users that have the `isOffline` flag set to `YES` will be skipped.

I hope this was helpful to you :)

**Comment by risp** [comment]
Great just what I was looking for! Thanks

**Comment by 3lvis** [comment]
:tada: :smile: :tada:
