### ISSUE TITLE
Foreign key relationship

### ISSUE THREAD

**Issue by risp** [hyperoslo/Sync#64]
Hi guys,

Really like this pod so far, nice work! I was wondering if foreign key relationship is supported. Say you have this json:

```json
{ "project":
    {   "id": 12345,
        "name": "My Project",
        "category": 1,
        "teamMemberIDs": [1, 2, 3, 4]
    }
 }
```

where the category would be a relation to a category and the teamMemberIDs a relation to multiple users.

**Comment by 3lvis** [comment]
Hi @risp!

Yes we have support for that but your JSON would have to look a bit different.

```json
{
  "id":12345,
  "name":"My Project",
  "category":{
    "id":231,
    "title":"Category name"
  },
  "members":[
    {
      "id":1,
      "name":"Member 1"
    },
    {
      "id":2,
      "name":"Member 2"  
    }
  ]
}
```

Then in your Core Data Model you'll have

Project ----- (to one)----> Category
Project ----- (to many)----> Member

**Comment by 3lvis** [comment]
Is that what you meant?

Take a look at the Tests project, it has various Core Data entities supporting all sorts of combinations.

We also have all sorts of `JSON` files that could help you as examples

https://github.com/hyperoslo/Sync/tree/master/Tests/Tests

**Comment by risp** [comment]
Thanks, I found the `Tests` project already and it helped a lot. But in this case we designed our API to use as less bandwidth as possible so therefore we are only sending the `id` instead of the `object`. Of course in this example the difference in bandwidth is small but when there are a lot of objects in the response it increases fast.  It would be really nice if this could be supported as well because there are also external API's that use this kind of foreign keys in their JSON.

**Comment by 3lvis** [comment]
Oh, I totally understand why this is build.

@risp I see, what do you use the ids for? You still have to ask for their data right?

I agree, this is a common use case. Lets see if we can find a way to support it in Sync :)

**Comment by 3lvis** [comment]
Let me know how we can help :)

**Comment by risp** [comment]
> @risp I see, what do you use the ids for? You still have to ask for their data right?

Yes, that's right. In my project, objects have a category, project, paymentMethod. When the user logs in I preload these all so that from then on IDs can be used instead of the object.

**Comment by 3lvis** [comment]
I think you can still use `Sync` and in your main `JSON` just skip this IDs, and then when you get to the object detail you'll retrieve the JSON with the full details.

I might be wrong but let me know if we can improve Sync in a way the is more helpful for you. :)

**Comment by 3lvis** [comment]
I've been working on this in #140

Should be ready at the end of next week.
