### ISSUE TITLE
JSON Mapping for child objects

### ISSUE THREAD

**Issue by benvium** [hyperoslo/Sync#66]
My goal is to map JSON which looks like this..

```json
[
  {
    "id": "1",
    "a": {
      "b": {
        "name": "hello"
      }
    }
  }
]
```

.. to an NSManagedObject that looks like this:

```
@property (nonatomic, retain) NSString * remoteID;
@property (nonatomic, retain) NSString * name;
```

.. So that I can sync it using your library (which is great by the way).

There's nothing useful at the 'a' and 'b' levels, so I don't really want to create relationships for them.

I tried putting:

```
hyper.remoteKey = a.b.name
```

.. into the xcdatamodel file, but no luck. 

Any ideas? I suppose I could pre-process the NSDictionary before I pass it into Sync?

**Comment by 3lvis** [comment]
Hi Ben,

You're right, at the moment Sync requires you to have a `primary key` per JSON object. It doesn't really have to be `id`, it can be anything but by default it tries to use `id`.

At the moment you'll have to preprocess the JSON in order for Sync to work.

I hope this was useful for you :)

**Comment by benvium** [comment]
Ok, thanks for the response.
