### ISSUE TITLE
Crash with nil localKey and remoteID

### ISSUE THREAD

**Issue by pettersamuelsen** [hyperoslo/Sync#68]
I have a json structure that looks something like this:

```json
{
    "name": "...",
    "id": "...",
    "foo": {
        "bar": "..."
    }
}
``` 
`foo` is a seperate entity with no primary key. The `NSFetchRequest` crashes in `safeObjectInContext:entityName:remoteID:` due to nil comparison in the `NSPredicate`: https://github.com/hyperoslo/Sync/blob/master/Source/Sync.m#L147

**Comment by 3lvis** [comment]
Hi Petter!

It's a requirement that all JSON objects have a `remoteID` if they have a matching Core Data model.

You could either add a `remoteID` to `foo` or mark `bar` as primary key by doing.

```
foo => hyper.isPrimaryKey : YES
```

![d](https://raw.githubusercontent.com/hyperoslo/Sync/master/Images/custom-primary-key-v2.png)

**Comment by 3lvis** [comment]
I hope this was helful!

**Comment by pettersamuelsen** [comment]
Thanks for the quick reply, Elvis!
Is it required for all entities to have a primary key by design or are you open for a PR that will fix this?

**Comment by 3lvis** [comment]
PR would be awesome!
