### ISSUE TITLE
No primary key causes crash

### ISSUE THREAD

**Issue by bonebox** [hyperoslo/Sync#79]
I noticed while attempting to integrate Sync into a separate project, that if I don't have either a remoteID property (and corresponding "id" property in the JSON) or hyper.isPrimaryKey specified for a property on that entity, that the app crashes with an EXC_BAD_ACCESS on line 148 of Sync.m.  It appears that the issue is that both remoteID and localKey are nil.  I then added an "id" property to every object in my JSON and a matching remoteID property to each entity in my model, and it works.  Is this intentional?  There are cases where a primary key isn't always desired for every entity.

**Comment by 3lvis** [comment]
Hi @bonebox! 

At the moment Sync requires your entities to have a primary key, this is important for diffing otherwise Sync doesn't know how to differentiate this entity with the others.

You're primary key doesn't have to be `remoteID`, `uniqueID` or anything like that. In the Designer News example we have a `Comment` entity that uses `body` as the primary key.

https://github.com/hyperoslo/Sync/tree/master/Examples/DesignerNews

**Comment by 3lvis** [comment]
@bonebox I'll improve the README to state that. 

I hope this helps :)

**Comment by bonebox** [comment]
Thanks for the clarification. So what happens if the body property of a Comment entity just so happens to have the same value as a completely different comment in the JSON?  If there are 2 of the same type of object that have the same value for a property designated as primary key, only one is kept, correct?  I may have a nested object off a root object that could potentially have the same property value(s) as another of the same type of object off another root object--but they should be considered separate objects in the database.  So then that's not possible with Sync?

**Comment by 3lvis** [comment]
It takes the parent in account too, so a child ID should be unique per parent, not globally.

I guess this would be different in a many-to-many relationship, in that case child IDs are required to be unique globally.

**Comment by bonebox** [comment]
Ok, that's good to know.  Thanks again for the clarification!
