### ISSUE TITLE
Request - Support Storing JSON in Dictionaries/Arrays

### ISSUE THREAD

**Issue by bonebox** [hyperoslo/Sync#87]
Sometimes JSON can look like the following, which is a dictionary with dynamic keys.

```
"inputConfiguration":  {
     "justAHint" : [ "a",  "b" ],
   "keyboardConfiguration": "telephone",
   "someOtherConfiguration": { "this": "that", "here": "there"}
  },
```

Or even a dictionary with a static key, but an array of objects (no keys):

```
"aliasLabels" : ["Option Three A", "Option Three B"]
```
These are obviously difficult to map into objects.  Core Data allows storing Dictionaries and Arrays as a transformable attribute type.  It would be great if Sync allowed storing a part of the JSON in this manner.  

One way it could work, to use my `inputConfiguration` example above, would be to create a corresponding Core Data attribute called `inputConfiguration` with a transformable type, and defined as a dictionary in its entity's class definition.  Then have another user info key/value pair, for instance `hyper.isCollection`, which would tell Sync not to map that out into objects, but instead just store that part of the JSON in the `inputConfiguration` attribute as a dictionary.  

It could theoretically work the same way for the array of objects with no keys in my 2nd example.  Normally Sync would see that and think it's a relationship to be mapped, but perhaps when it doesn't find a relationship named `aliasLabels` in the Core Data model, it could then check for an attribute by that same name and if it has the `hyper.isCollection` (or whatever) key/value pair, just store that piece of JSON as an array.

### Mapping Option
A separate (nicer, but more complex) idea I had for actually mapping this type of JSON out into objects, could go something like this:  

For the array with no keys (to use my example again), you would still have your typical to-many relationship called `aliasLabels` to another entity.  The entity should have a single attribute (string in this case).  Sync could either deduce from there only being one attribute that this must be the attribute to map the value to, or a new `hyper.defaultValue` (or whatever) user info key/value pair could be used to indicate this is the attribute to map to.

The dictionary with dynamic keys would probably be a lot more difficult to map, since it could contain any number of objects.  So it would have to be treated as a to-many relationship, and each of those key/value pairs as a separate entity.  Then in those entities you would need at least 2 attributes; one to store the dynamic key, and another for the actual value.  Then you would of course have to define a user info key/value pair for them, such as `hyper.dynamicKey` and `hyper.defaultValue` so Sync would know which to map into.  That would work for dictionaries with dynamic keys where the objects are always the same, but unfortunately still wouldn't work with my example above, since those objects themselves can be anything.  That's where being able to store the data as a dictionary/array would still be nice.

Sorry for the long post, but I really like this library and think having support for a broader type of potential JSON would make it even more useful.

**Comment by 3lvis** [comment]
Hi @bonebox!

Very interesting write up, you have valid points and we indeed considered storing dictionaries and arrays, I hope is what you were looking for.

For mapping for arrays and dictionaries just set attributes as `Binary Data` on the Core Data modeler

![screen shot 2015-04-02 at 11 10 11 pm](https://cloud.githubusercontent.com/assets/1088217/6973785/7d3767dc-d98d-11e4-8add-9c9421b5ed47.png)

# Array
```objc
NSDictionary *values = @{@"hobbies" : @[@"football",
                                        @"soccer",
                                        @"code"]};

[managedObject hyp_fillWithDictionary:values];

NSString *hobby = [NSKeyedUnarchiver unarchiveObjectWithData:managedObject.hobbies][0];
// ==> "football"
```

# Dictionary
```objc
NSDictionary *values = @{@"expenses" : @{@"cake" : @12.50,
                                         @"juice" : @0.50}};

[managedObject hyp_fillWithDictionary:values];

NSNumber *price = [NSKeyedUnarchiver unarchiveObjectWithData managedObject.expenses][@"cake"];
// ==> 12.50
```

Please let me know if this is what you wanted :)

I'll make sure to add this to the README.

**Comment by bonebox** [comment]
Hey @3lvis, that sounds awesome! Unfortunately I can't seem to get it working.  The binary data attribute value remain nil after mapping.  Is there any other configuration that needs to be done?  Do you have a test project where this is working? Thanks!

**Comment by bonebox** [comment]
Here's an actual example that's not working for me.  Trying to map `inputConfiguration` into a binary data (NSData) attribute.
![screen shot 2015-04-23 at 5 35 04 pm](https://cloud.githubusercontent.com/assets/1120504/7308984/411520de-e9df-11e4-983e-72e033294526.png)


```
"elements" : [
     {
      "type": "input",
       "label": "Any Input",
       "reference": "anyInteger",
       "inputConfiguration": {
            "justAHint" : ["a", "b", "c"]
          }
     },
    ...
]

**Comment by 3lvis** [comment]
We use snake_case for the JSON, also for Sync `inputConfiguration ` is an entity with a `to-one` relationships with `just_a_hint`, it doesn't infer that if should take the contents from inside `justAHint`. The following should work.

```json
"elements" : [
     {
      "type": "input",
       "label": "Any Input",
       "reference": "anyInteger",
       "input_configuration": ["a", "b", "c"]
     },
    ...
]
```

**Comment by 3lvis** [comment]
I've been thinking on supporting mapping depth entities like the one in your example but haven't got around into doing it.

For example if you had the following JSON: 
```json
"elements" : [
     {
       "input_configuration": {
            "just_a_hint" : ["a", "b", "c"]
          }
     },
    ...
]
```

Mapping the contents of `just_a_hint` to `input_configuration` could be done by adding the following key to the user info of your attribute:

```
"hyper.remoteKey" : "input_configuration.just_a_hint"
```

And then when you want to make the JSON representation of your element:

```objc
// This makes a JSON representation of your NSManagedObject subclass
[self.managedObject hyp_dictionary];
```
This would be (we will have to use the `.` as a separation between levels:

input_configuration`.`just_a_hint

```json
{
    "input_configuration": {
      "just_a_hint" : ["a", "b", "c"]
    }
}
```

**Comment by bonebox** [comment]
>We use snake_case for the JSON keys.

Ah, that did the trick!  I did remember reading that if the JSON uses snake_case then the core data equivalent needed to be camelCase, but didn't realize that snake_case was an actual requirement for the JSON key. Thankfully we control the JSON also, so I can have that updated. 

>I've been thinking on supporting mapping depth entities like the one in your example but haven't got around into doing it.

That looks really cool!  Would it support having multiple entries in the dictionary?  For example:

```
 "inputConfiguration": {
       "justAHint" : ["a", "b", "c"],
       "anotherHint" : ["d", "e", "f"]
 }
```

Thanks again for all the help!

**Comment by 3lvis** [comment]
>That looks really cool! Would it support having multiple entries in the dictionary? For example:

Interesting! I'll add this to the main task for reference.

https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/issues/64

**Comment by bonebox** [comment]
Awesome, thanks!!!

**Comment by bonebox** [comment]
@3lvis Out of curiosity, is there reason for the snake_case requirement for JSON keys?  It seems like as long as the JSON key matches the core data attribute (with the exception of reserved types), that should work as well.

**Comment by bonebox** [comment]
@3lvis I probably should have tried this before, but I was able to get it to work with the existing JSON key by simply doing `"hyper.remoteKey" : "inputConfiguration"`.

**Comment by 3lvis** [comment]
@bonebox We tried to model Sync to work out of the box for the most used scenarios, you could say that it has been "optimized" to work with Ruby or Rails kind of backends. Having less options helps the app to have less ways to fail.

:smile:
