### ISSUE TITLE
Add ability to cancel Sync operation

### ISSUE THREAD

**Issue by kostiakoval** [hyperoslo/Sync#93]
I would like to be able to cancel Sync operation. 
When I call sync It should probably return Sync Operation the would have a cancel method.
```objc
 Sync *operation = [Sync changes:JSON
inEntityNamed:@"User"
    predicate:predicate
    dataStack:dataStack
   completion:^{
       //...
    }];
[operation cancel];
```

**Comment by 3lvis** [comment]
Interesting :)

**Comment by kostiakoval** [comment]
Yes I also was thinking about it

**Comment by 3lvis** [comment]
“Advanced NSOperations (WWDC 2015)” by @davedelong.

**Comment by 3lvis** [comment]
Fixed on https://github.com/hyperoslo/Sync/pull/216
